// src/components/ffmpeg/ProgressBar.tsx
import React from 'react';

interface ProgressBarProps {
  value: number;
  label?: string;
}

export function ProgressBar({ value, label }: ProgressBarProps) {
  return (
    <div className="space-y-1">
      {label && (
        <div className="flex justify-between text-xs">
          <span style={{ color: 'var(--text-secondary)' }}>{label}</span>
          <span className="font-mono" style={{ color: 'var(--primary-color)' }}>{value}%</span>
        </div>
      )}
      <div
        className="h-2 rounded-full overflow-hidden"
        style={{ backgroundColor: 'var(--bg-tertiary)' }}
      >
        <div
          className="h-full rounded-full transition-all duration-300"
          style={{
            width: `${value}%`,
            background: 'linear-gradient(90deg, var(--primary-color), #8b5cf6)',
          }}
        />
      </div>
    </div>
  );
}

// 项目重构/src/components/ffmpeg/ProgressBar.vue
<script setup lang="ts">
defineProps<{
  value: number;
  label?: string;
  color?: 'blue' | 'green' | 'red' | 'purple';
}>();
</script>

<template>
  <div class="progress-bar-container">
    <div v-if="label" class="progress-label">{{ label }}</div>
    <div class="progress-bar">
      <div 
        class="progress-fill"
        :class="color || 'blue'"
        :style="{ width: `${Math.min(100, Math.max(0, value))}%` }"
      />
    </div>
    <span class="progress-value">{{ value }}%</span>
  </div>
</template>

<style scoped>
.progress-bar-container {
  display: flex;
  align-items: center;
  gap: 8px;
}

.progress-label {
  font-size: 11px;
  color: var(--text-tertiary);
  white-space: nowrap;
}

.progress-bar {
  flex: 1;
  height: 6px;
  background-color: var(--bg-tertiary);
  border-radius: 3px;
  overflow: hidden;
}

.progress-fill {
  height: 100%;
  border-radius: 3px;
  transition: width 0.3s ease;
}

.progress-fill.blue {
  background: linear-gradient(90deg, #3b82f6, #60a5fa);
}

.progress-fill.green {
  background: linear-gradient(90deg, #10b981, #34d399);
}

.progress-fill.red {
  background: linear-gradient(90deg, #ef4444, #f87171);
}

.progress-fill.purple {
  background: linear-gradient(90deg, #8b5cf6, #a78bfa);
}

.progress-value {
  font-size: 11px;
  color: var(--text-tertiary);
  min-width: 32px;
  text-align: right;
}
</style>
