// src/components/ChatControlPanel.tsx
import { useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useStore } from '@/store';
import { useToast } from '@/components/Toast';
import { configStorage } from '@/services/storage/ConfigStorage';
import { Activity, Brain, MessageCircle, Image as ImageIcon, AlertTriangle, Settings2, X } from 'lucide-react';

interface ChatControlPanelProps {
  isOpen: boolean;
  onClose: () => void;
  onToggle: () => void;
}

export function ChatControlPanel({ isOpen, onClose, onToggle }: ChatControlPanelProps) {
  const toast = useToast();
  const containerRef = useRef<HTMLDivElement>(null);
  
  const {
    ollamaVerboseMode, setOllamaVerboseMode,
    ollamaThinkMode, setOllamaThinkMode,
    ollamaChatMode, setOllamaChatMode,
    includeImagesInContext, setIncludeImagesInContext,
    deleteConfirmEnabled, setDeleteConfirmEnabled,
  } = useStore();

  useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        onClose();
      }
    };

    if (isOpen) {
      setTimeout(() => {
        document.addEventListener('mousedown', handleClickOutside);
      }, 0);
    }

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [isOpen, onClose]);

  const controls = [
    {
      id: 'deleteConfirm',
      icon: AlertTriangle,
      label: '删除确认',
      checked: deleteConfirmEnabled,
      onChange: () => {
        const newValue = !deleteConfirmEnabled;
        setDeleteConfirmEnabled(newValue);
        configStorage.set('deleteConfirmEnabled', newValue);
        toast.info(newValue ? '已开启删除确认' : '已关闭删除确认', { duration: 2000 });
      },
    },
    {
      id: 'verbose',
      icon: Activity,
      label: '详细模式',
      checked: ollamaVerboseMode,
      onChange: () => {
        const newValue = !ollamaVerboseMode;
        setOllamaVerboseMode(newValue);
        configStorage.set('ollamaVerboseMode', newValue);
        toast.info(newValue ? '已开启详细模式' : '已关闭详细模式', { duration: 2000 });
      },
    },
    {
      id: 'think',
      icon: Brain,
      label: '思考模式',
      checked: ollamaThinkMode,
      onChange: () => {
        const newValue = !ollamaThinkMode;
        setOllamaThinkMode(newValue);
        configStorage.set('ollamaThinkMode', newValue);
        toast.info(newValue ? '已开启思考模式' : '已关闭思考模式', { duration: 2000 });
      },
    },
    {
      id: 'chat',
      icon: MessageCircle,
      label: '多轮对话',
      checked: ollamaChatMode === 'multi',
      onChange: () => {
        const newMode = ollamaChatMode === 'multi' ? 'single' : 'multi';
        setOllamaChatMode(newMode);
        configStorage.set('ollamaChatMode', newMode);
        toast.info(newMode === 'multi' ? '已切换到多轮对话模式' : '已切换到单轮对话模式', { duration: 2000 });
      },
    },
    {
      id: 'images',
      icon: ImageIcon,
      label: '携带图片',
      checked: includeImagesInContext,
      onChange: () => {
        const newValue = !includeImagesInContext;
        setIncludeImagesInContext(newValue);
        configStorage.set('includeImagesInContext', newValue);
        toast.info(newValue ? '多轮对话将携带图片数据' : '多轮对话将不携带图片数据', { duration: 2000 });
      },
    },
  ];

  return (
    <div className="relative" ref={containerRef}>
      <button
        onClick={onToggle}
        className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl transition-all duration-200 hover:scale-110"
        style={{
          backgroundColor: isOpen ? 'var(--primary-color)' : 'var(--bg-secondary)',
          color: isOpen ? 'white' : 'var(--text-tertiary)',
          border: '1px solid var(--border-color)',
        }}
        title={isOpen ? '隐藏聊天控制' : '显示聊天控制'}
      >
        <Settings2 size={18} style={{ color: 'inherit' }} />
      </button>

      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ y: 10, opacity: 0, scale: 0.95 }}
            animate={{ y: 0, opacity: 1, scale: 1 }}
            exit={{ y: 10, opacity: 0, scale: 0.95 }}
            transition={{ type: 'spring', damping: 25, stiffness: 400 }}
            className="absolute bottom-full right-0 mb-3 z-50"
          >
            <div
              className="rounded-2xl overflow-hidden"
              style={{
                backgroundColor: 'var(--bg-primary)',
                border: '1px solid var(--border-color)',
                boxShadow: '0 8px 32px rgba(0, 0, 0, 0.12)',
                width: '220px',
              }}
            >
              <div
                className="flex items-center justify-between px-4 py-2.5 border-b"
                style={{ borderColor: 'var(--border-color)' }}
              >
                <span className="text-xs font-semibold" style={{ color: 'var(--text-primary)' }}>聊天控制</span>
                <button
                  onClick={onClose}
                  className="p-1 rounded-md transition-all duration-150 hover:scale-110 hover:bg-[var(--bg-secondary)]"
                  style={{ color: 'var(--text-tertiary)' }}
                >
                  <X size={14} />
                </button>
              </div>

              <div className="p-2 space-y-1">
                {controls.map((control) => (
                  <motion.div
                    key={control.id}
                    whileHover={{ scale: 1.02 }}
                    whileTap={{ scale: 0.98 }}
                    className="flex items-center justify-between px-3 py-2.5 rounded-xl transition-all duration-150 cursor-pointer"
                    style={{
                      backgroundColor: control.checked ? 'var(--primary-light)' : 'var(--bg-secondary)',
                    }}
                    onClick={control.onChange}
                  >
                    <div className="flex items-center gap-2.5">
                      <div
                        className="flex items-center justify-center w-7 h-7 rounded-lg transition-all duration-200"
                        style={{
                          backgroundColor: control.checked ? 'var(--primary-color)' : 'var(--bg-tertiary)',
                        }}
                      >
                        <control.icon
                          size={14}
                          style={{ color: control.checked ? 'white' : 'var(--text-tertiary)' }}
                        />
                      </div>
                      <span
                        className="text-xs font-medium"
                        style={{ color: control.checked ? 'var(--primary-color)' : 'var(--text-primary)' }}
                      >
                        {control.label}
                      </span>
                    </div>
                    <div
                      className="relative w-9 h-5 rounded-full shrink-0 transition-all duration-200"
                      style={{
                        backgroundColor: control.checked ? 'var(--primary-color)' : 'var(--bg-tertiary)',
                      }}
                    >
                      <motion.div
                        className="absolute top-0.5 w-4 h-4 rounded-full"
                        style={{
                          backgroundColor: 'white',
                          boxShadow: '0 1px 3px rgba(0, 0, 0, 0.15)',
                        }}
                        animate={{
                          x: control.checked ? 16 : 2,
                        }}
                        transition={{ type: 'spring', stiffness: 500, damping: 30 }}
                      />
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// 项目重构/src/components/chat/ChatControlPanel.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue';
import { Activity, Brain, MessageCircle, Image as ImageIcon, AlertTriangle, Settings2, X, EyeOff, Navigation } from 'lucide-vue-next';
import { useConversationStore } from '@/stores';
import { useToast } from '@/composables/useToast';

interface Props {
  isOpen: boolean;
}

const props = defineProps<Props>();
const emit = defineEmits<{
  close: [];
  toggle: [];
}>();

const conversationStore = useConversationStore();
const toast = useToast();
const containerRef = ref<HTMLElement | null>(null);

const controls = computed(() => [
    {
      id: 'deleteConfirm',
      icon: AlertTriangle,
      label: '删除确认',
      checked: conversationStore.deleteConfirmEnabled,
      onChange: () => {
        const newValue = !conversationStore.deleteConfirmEnabled;
        conversationStore.setDeleteConfirmEnabled(newValue);
        toast.info(newValue ? '已开启删除确认' : '已关闭删除确认');
      },
    },
    {
      id: 'autoHideInput',
      icon: EyeOff,
      label: '自动隐藏输入框',
      checked: conversationStore.autoHideInputEnabled,
      onChange: () => {
        const newValue = !conversationStore.autoHideInputEnabled;
        conversationStore.setAutoHideInputEnabled(newValue);
        toast.info(newValue ? '已开启自动隐藏' : '已关闭自动隐藏');
      },
    },
    {
      id: 'verboseMode',
      icon: Activity,
      label: '详细模式',
      checked: conversationStore.ollamaVerboseMode,
      onChange: () => {
        const newValue = !conversationStore.ollamaVerboseMode;
        conversationStore.setOllamaVerboseMode(newValue);
        toast.info(newValue ? '已开启详细模式' : '已关闭详细模式');
      },
    },
    {
      id: 'thinkMode',
      icon: Brain,
      label: '思考模式',
      checked: conversationStore.ollamaThinkMode,
      onChange: () => {
        const newValue = !conversationStore.ollamaThinkMode;
        conversationStore.setOllamaThinkMode(newValue);
        toast.info(newValue ? '已开启思考模式' : '已关闭思考模式');
      },
    },
    {
      id: 'includeImages',
      icon: ImageIcon,
      label: '图片上下文',
      checked: conversationStore.includeImagesInContext,
      onChange: () => {
        const newValue = !conversationStore.includeImagesInContext;
        conversationStore.setIncludeImagesInContext(newValue);
        toast.info(newValue ? '已开启图片上下文' : '已关闭图片上下文');
      },
    },
    {
      id: 'showNavigationDots',
      icon: Navigation,
      label: '导航点',
      checked: conversationStore.showNavigationDots,
      onChange: () => {
        const newValue = !conversationStore.showNavigationDots;
        conversationStore.setShowNavigationDots(newValue);
        toast.info(newValue ? '已显示导航点' : '已隐藏导航点');
      },
    },
  ]);

const handleClickOutside = (event: MouseEvent) => {
  if (containerRef.value && !containerRef.value.contains(event.target as Node)) {
    emit('close');
  }
};

onMounted(() => {
  if (props.isOpen) {
    setTimeout(() => {
      document.addEventListener('mousedown', handleClickOutside);
    }, 0);
  }
});

onUnmounted(() => {
  document.removeEventListener('mousedown', handleClickOutside);
});
</script>

<template>
  <div class="relative" ref="containerRef">
    <button
      @click="emit('toggle')"
      class="control-btn"
      :class="{ 'is-open': isOpen }"
      title="聊天控制"
    >
      <Settings2 :size="18" />
    </button>

    <Transition name="panel">
      <div v-if="isOpen" class="control-panel">
        <div class="panel-header">
          <span class="panel-title">聊天控制</span>
          <button
            @click="emit('close')"
            class="close-btn"
          >
            <X :size="14" />
          </button>
        </div>

        <div class="panel-content">
          <div
            v-for="control in controls"
            :key="control.id"
            class="control-item"
            :class="{ 'is-active': control.checked }"
            @click="control.onChange"
          >
            <div class="control-left">
              <div class="control-icon" :class="{ 'is-active': control.checked }">
                <component :is="control.icon" :size="14" />
              </div>
              <span class="control-label" :class="{ 'is-active': control.checked }">
                {{ control.label }}
              </span>
            </div>
            <div class="toggle-switch" :class="{ 'is-active': control.checked }">
              <div class="toggle-thumb"></div>
            </div>
          </div>
        </div>
      </div>
    </Transition>
  </div>
</template>

<style scoped>
.control-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 36px;
  height: 36px;
  border-radius: 12px;
  background-color: var(--bg-secondary);
  color: var(--text-tertiary);
  border: 1px solid var(--border-color);
  cursor: pointer;
  transition: all 0.2s ease;
  flex-shrink: 0;
}

.control-btn:hover {
  transform: scale(1.1);
}

.control-btn.is-open {
  background-color: var(--primary-color);
  color: white;
}

.control-panel {
  position: absolute;
  top: 100%;
  right: 0;
  margin-top: 8px;
  width: 220px;
  border-radius: 16px;
  overflow: hidden;
  background-color: var(--bg-primary);
  border: 1px solid var(--border-color);
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.12);
  z-index: 1000;
}

.panel-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 16px;
  border-bottom: 1px solid var(--border-color);
}

.panel-title {
  font-size: 12px;
  font-weight: 600;
  color: var(--text-primary);
}

.close-btn {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 4px;
  border-radius: 6px;
  background: transparent;
  border: none;
  color: var(--text-tertiary);
  cursor: pointer;
  transition: all 0.15s ease;
}

.close-btn:hover {
  background-color: var(--bg-secondary);
  transform: scale(1.1);
}

.panel-content {
  padding: 8px;
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.control-item {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 10px 12px;
  border-radius: 12px;
  background-color: var(--bg-secondary);
  cursor: pointer;
  transition: all 0.15s ease;
}

.control-item:hover {
  transform: scale(1.02);
}

.control-item:active {
  transform: scale(0.98);
}

.control-item.is-active {
  background-color: var(--primary-light);
}

.control-left {
  display: flex;
  align-items: center;
  gap: 10px;
}

.control-icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 28px;
  height: 28px;
  border-radius: 8px;
  background-color: var(--bg-tertiary);
  color: var(--text-tertiary);
  transition: all 0.2s ease;
}

.control-icon.is-active {
  background-color: var(--primary-color);
  color: white;
}

.control-label {
  font-size: 12px;
  font-weight: 500;
  color: var(--text-primary);
  transition: color 0.2s ease;
}

.control-label.is-active {
  color: var(--primary-color);
}

.toggle-switch {
  position: relative;
  width: 36px;
  height: 20px;
  border-radius: 999px;
  background-color: var(--bg-tertiary);
  transition: background-color 0.2s ease;
  flex-shrink: 0;
}

.toggle-switch.is-active {
  background-color: var(--primary-color);
}

.toggle-thumb {
  position: absolute;
  top: 2px;
  left: 2px;
  width: 16px;
  height: 16px;
  border-radius: 50%;
  background-color: white;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.15);
  transition: transform 0.2s ease;
}

.toggle-switch.is-active .toggle-thumb {
  transform: translateX(16px);
}

.panel-enter-active,
.panel-leave-active {
  transition: all 0.2s ease;
}

.panel-enter-from,
.panel-leave-to {
  opacity: 0;
  transform: translateY(10px) scale(0.95);
}
</style>
