// src/components/ChatWelcome.tsx
import { MessageSquare, Sparkles, Bot, Zap, Shield, ArrowRight, Cpu, Brain, Timer, Image as ImageIcon, Code, BookOpen, PenTool, Send } from 'lucide-react';
import { motion } from 'framer-motion';
import { useStore } from '@/store';

interface ChatWelcomeProps {
  onStartChat: () => void;
  onSuggestionClick?: (text: string) => void;
}

export function ChatWelcome({ onStartChat, onSuggestionClick }: ChatWelcomeProps) {
  const { activeOllamaModel, ollamaStatus, ollamaModels } = useStore();

  const suggestions = [
    { icon: <Code size={16} />, text: '你叫什么，你是谁？' },
    { icon: <BookOpen size={16} />, text: '解释一下量子计算的原理' },
    { icon: <PenTool size={16} />, text: '写一篇关于人工智能的文章' },
    { icon: <ImageIcon size={16} />, text: '分析这张图片的内容' },
  ];

  const stats = [
    { value: ollamaModels.length, label: '可用模型' },
    { value: '100%', label: '本地运行' },
    { value: '∞', label: '对话次数' },
  ];

  return (
    <div 
      className="flex-1 flex flex-col overflow-hidden relative"
      style={{ backgroundColor: 'var(--bg-primary)' }}
    >
      {/* Animated Background */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div 
          className="absolute top-0 left-1/4 w-[500px] h-[500px] rounded-full blur-[100px] animate-pulse"
          style={{ 
            backgroundColor: 'var(--primary-color)',
            opacity: 0.08,
            animationDuration: '4s',
          }}
        />
        <div 
          className="absolute bottom-0 right-1/4 w-[400px] h-[400px] rounded-full blur-[80px]"
          style={{ 
            backgroundColor: '#8b5cf6',
            opacity: 0.06,
          }}
        />
      </div>

      {/* Main Content */}
      <div className="flex-1 flex flex-col items-center justify-center px-6 py-8 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="w-full max-w-2xl"
        >
          {/* Hero Section */}
          <div className="text-center mb-10">
            <motion.div
              initial={{ scale: 0.8, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              transition={{ duration: 0.5, delay: 0.1 }}
              className="inline-flex items-center justify-center w-16 h-16 rounded-2xl mb-6"
              style={{ 
                background: 'linear-gradient(135deg, var(--primary-color) 0%, #8b5cf6 50%, #ec4899 100%)',
                boxShadow: '0 12px 40px -12px rgba(139, 92, 246, 0.5)',
              }}
            >
              <Sparkles size={28} color="white" />
            </motion.div>

            <motion.h1 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.2 }}
              className="text-4xl font-bold mb-3"
              style={{ color: 'var(--text-primary)' }}
            >
              你好，我是 AI 助手
            </motion.h1>

            <motion.p 
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: 0.3 }}
              className="text-base max-w-md mx-auto"
              style={{ color: 'var(--text-secondary)' }}
            >
              基于 Ollama 本地运行，安全、私密、强大。有什么我可以帮助你的吗？
            </motion.p>
          </div>

          {/* Status Bar */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.35 }}
            className="flex items-center justify-center gap-6 mb-8"
          >
            {stats.map((stat, index) => (
              <div key={index} className="text-center">
                <div 
                  className="text-2xl font-bold"
                  style={{ color: 'var(--primary-color)' }}
                >
                  {stat.value}
                </div>
                <div 
                  className="text-xs"
                  style={{ color: 'var(--text-tertiary)' }}
                >
                  {stat.label}
                </div>
              </div>
            ))}
          </motion.div>

          {/* Input Box */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.4 }}
            onClick={onStartChat}
            className="relative mb-6 cursor-pointer group"
          >
            <div 
              className="flex items-center gap-3 p-4 rounded-2xl transition-all group-hover:shadow-lg"
              style={{ 
                backgroundColor: 'var(--bg-secondary)',
                border: '1px solid var(--border-color)',
              }}
            >
              <div 
                className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
                style={{ backgroundColor: 'var(--primary-light)' }}
              >
                <MessageSquare size={18} style={{ color: 'var(--primary-color)' }} />
              </div>
              <span 
                className="flex-1 text-sm"
                style={{ color: 'var(--text-tertiary)' }}
              >
                输入消息开始对话...
              </span>
              <div 
                className="w-10 h-10 rounded-xl flex items-center justify-center transition-all group-hover:scale-105"
                style={{ 
                  backgroundColor: 'var(--primary-color)',
                  boxShadow: '0 4px 12px rgba(0, 0, 0, 0.15)',
                }}
              >
                <ArrowRight size={18} color="white" />
              </div>
            </div>
          </motion.div>

          {/* Suggestions */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.5 }}
            className="space-y-2"
          >
            <div 
              className="text-xs font-medium text-center mb-3"
              style={{ color: 'var(--text-tertiary)' }}
            >
              试试这些
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {suggestions.map((suggestion, index) => (
                <motion.button
                  key={index}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.3, delay: 0.55 + index * 0.05 }}
                  onClick={() => {
                    if (onSuggestionClick) {
                      onSuggestionClick(suggestion.text);
                    } else {
                      onStartChat();
                    }
                  }}
                  className="flex items-center gap-3 p-3 rounded-xl text-left transition-all hover:scale-[1.01] active:scale-[0.99]"
                  style={{ 
                    backgroundColor: 'var(--bg-secondary)',
                    border: '1px solid var(--border-color)',
                  }}
                >
                  <div 
                    className="w-8 h-8 rounded-lg flex items-center justify-center flex-shrink-0"
                    style={{ backgroundColor: 'var(--bg-tertiary)' }}
                  >
                    <span style={{ color: 'var(--text-secondary)' }}>{suggestion.icon}</span>
                  </div>
                  <span 
                    className="text-sm truncate"
                    style={{ color: 'var(--text-secondary)' }}
                  >
                    {suggestion.text}
                  </span>
                </motion.button>
              ))}
            </div>
          </motion.div>

          {/* Model Status */}
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.7 }}
            className="mt-8 flex items-center justify-center gap-2"
          >
            <div 
              className={`w-2 h-2 rounded-full ${ollamaStatus?.isRunning ? 'animate-pulse' : ''}`}
              style={{ backgroundColor: ollamaStatus?.isRunning ? 'var(--success-color)' : 'var(--error-color)' }}
            />
            <span 
              className="text-xs"
              style={{ color: 'var(--text-tertiary)' }}
            >
              {ollamaStatus?.isRunning 
                ? <>{activeOllamaModel || `${ollamaModels.length} 个模型可用`} · 点击开始</>
                : 'Ollama 未运行，请先启动服务'
              }
            </span>
          </motion.div>
        </motion.div>
      </div>

      {/* Bottom Features */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.6 }}
        className="flex items-center justify-center gap-8 py-6 px-6 relative z-10"
        style={{ 
          borderTop: '1px solid var(--border-color)',
          backgroundColor: 'var(--bg-secondary)',
        }}
      >
        {[
          { icon: <Shield size={16} />, text: '本地运行' },
          { icon: <Brain size={16} />, text: '深度思考' },
          { icon: <Timer size={16} />, text: '性能监控' },
          { icon: <ImageIcon size={16} />, text: '图像识别' },
        ].map((item, index) => (
          <div 
            key={index}
            className="flex items-center gap-2"
          >
            <span style={{ color: 'var(--text-tertiary)' }}>{item.icon}</span>
            <span 
              className="text-xs hidden sm:inline"
              style={{ color: 'var(--text-tertiary)' }}
            >
              {item.text}
            </span>
          </div>
        ))}
      </motion.div>
    </div>
  );
}

// 项目重构/src/components/chat/ChatWelcome.vue
<script setup lang="ts">
import { computed } from 'vue';
import { 
  MessageSquare, Sparkles, Shield, Brain, Timer, 
  Image as ImageIcon, Code, BookOpen, PenTool, ArrowRight 
} from 'lucide-vue-next';
import { useConversationStore } from '@/stores';

interface Props {
  onStartChat: () => void;
  onSuggestionClick?: (text: string) => void;
}

const props = defineProps<Props>();

const conversationStore = useConversationStore();

const suggestions = [
  { icon: Code, text: '你叫什么，你是谁？' },
  { icon: BookOpen, text: '解释一下量子计算的原理' },
  { icon: PenTool, text: '写一篇关于人工智能的文章' },
  { icon: ImageIcon, text: '分析这张图片的内容' },
];

const stats = computed(() => [
  { value: conversationStore.models.length, label: '可用模型' },
  { value: '100%', label: '本地运行' },
  { value: '∞', label: '对话次数' },
]);

const handleSuggestionClick = (text: string) => {
  if (props.onSuggestionClick) {
    props.onSuggestionClick(text);
  } else {
    props.onStartChat();
  }
};
</script>

<template>
  <div class="chat-welcome">
    <div class="animated-bg">
      <div class="bg-circle bg-circle-1"></div>
      <div class="bg-circle bg-circle-2"></div>
    </div>

    <div class="content-wrapper">
      <div class="hero-section">
        <div class="hero-icon">
          <Sparkles :size="28" color="white" />
        </div>

        <h1 class="hero-title">你好，我是 AI 助手</h1>
        <p class="hero-subtitle">
          基于 Ollama 本地运行，安全、私密、强大。有什么我可以帮助你的吗？
        </p>
      </div>

      <div class="stats-bar">
        <div v-for="(stat, index) in stats" :key="index" class="stat-item">
          <div class="stat-value">{{ stat.value }}</div>
          <div class="stat-label">{{ stat.label }}</div>
        </div>
      </div>

      <div class="input-box" @click="onStartChat">
        <div class="input-icon">
          <MessageSquare :size="18" />
        </div>
        <span class="input-placeholder">输入消息开始对话...</span>
        <div class="input-arrow">
          <ArrowRight :size="18" color="white" />
        </div>
      </div>

      <div class="suggestions-section">
        <div class="suggestions-title">试试这些</div>
        <div class="suggestions-grid">
          <button
            v-for="(suggestion, index) in suggestions"
            :key="index"
            class="suggestion-item"
            @click="handleSuggestionClick(suggestion.text)"
          >
            <div class="suggestion-icon">
              <component :is="suggestion.icon" :size="16" />
            </div>
            <span class="suggestion-text">{{ suggestion.text }}</span>
          </button>
        </div>
      </div>

      <div class="model-status">
        <div 
          class="status-dot"
          :class="{ 'status-active': conversationStore.activeModel }"
        ></div>
        <span class="status-text">
          {{ conversationStore.activeModel ? 
            `${conversationStore.activeModel.name} · 点击开始` : 
            '请先选择模型' 
          }}
        </span>
      </div>
    </div>

    <div class="features-bar">
      <div class="feature-item">
        <Shield :size="16" />
        <span>本地运行</span>
      </div>
      <div class="feature-item">
        <Brain :size="16" />
        <span>深度思考</span>
      </div>
      <div class="feature-item">
        <Timer :size="16" />
        <span>性能监控</span>
      </div>
      <div class="feature-item">
        <ImageIcon :size="16" />
        <span>图像识别</span>
      </div>
    </div>
  </div>
</template>

<style scoped>
.chat-welcome {
  flex: 1;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  position: relative;
  background-color: var(--bg-primary);
}

.animated-bg {
  position: absolute;
  inset: 0;
  overflow: hidden;
  pointer-events: none;
}

.bg-circle {
  position: absolute;
  border-radius: 50%;
  filter: blur(100px);
}

.bg-circle-1 {
  top: 0;
  left: 25%;
  width: 500px;
  height: 500px;
  background-color: var(--primary-color);
  opacity: 0.08;
  animation: pulse 4s ease-in-out infinite;
}

.bg-circle-2 {
  bottom: 0;
  right: 25%;
  width: 400px;
  height: 400px;
  background-color: #8b5cf6;
  opacity: 0.06;
  filter: blur(80px);
}

@keyframes pulse {
  0%, 100% { opacity: 0.08; }
  50% { opacity: 0.12; }
}

.content-wrapper {
  flex: 1;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 32px 24px;
  position: relative;
  z-index: 10;
  max-width: 672px;
  margin: 0 auto;
  width: 100%;
}

.hero-section {
  text-align: center;
  margin-bottom: 40px;
}

.hero-icon {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  width: 64px;
  height: 64px;
  border-radius: 16px;
  margin-bottom: 24px;
  background: linear-gradient(135deg, var(--primary-color) 0%, #8b5cf6 50%, #ec4899 100%);
  box-shadow: 0 12px 40px -12px rgba(139, 92, 246, 0.5);
}

.hero-title {
  font-size: 36px;
  font-weight: 700;
  color: var(--text-primary);
  margin-bottom: 12px;
}

.hero-subtitle {
  font-size: 16px;
  color: var(--text-secondary);
  max-width: 448px;
  margin: 0 auto;
}

.stats-bar {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 24px;
  margin-bottom: 32px;
}

.stat-item {
  text-align: center;
}

.stat-value {
  font-size: 24px;
  font-weight: 700;
  color: var(--primary-color);
}

.stat-label {
  font-size: 12px;
  color: var(--text-tertiary);
}

.input-box {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 16px;
  border-radius: 16px;
  background-color: var(--bg-secondary);
  border: 1px solid var(--border-color);
  cursor: pointer;
  transition: all 0.2s ease;
  margin-bottom: 24px;
  width: 100%;
}

.input-box:hover {
  box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);
}

.input-icon {
  width: 40px;
  height: 40px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--primary-light);
  color: var(--primary-color);
  flex-shrink: 0;
}

.input-placeholder {
  flex: 1;
  font-size: 14px;
  color: var(--text-tertiary);
}

.input-arrow {
  width: 40px;
  height: 40px;
  border-radius: 12px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--primary-color);
  box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
  transition: transform 0.2s ease;
}

.input-box:hover .input-arrow {
  transform: scale(1.05);
}

.suggestions-section {
  width: 100%;
  margin-bottom: 32px;
}

.suggestions-title {
  font-size: 12px;
  font-weight: 500;
  text-align: center;
  color: var(--text-tertiary);
  margin-bottom: 12px;
}

.suggestions-grid {
  display: grid;
  grid-template-columns: repeat(2, 1fr);
  gap: 8px;
}

.suggestion-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  border-radius: 12px;
  background-color: var(--bg-secondary);
  border: 1px solid var(--border-color);
  cursor: pointer;
  transition: all 0.2s ease;
  text-align: left;
}

.suggestion-item:hover {
  transform: scale(1.01);
}

.suggestion-item:active {
  transform: scale(0.99);
}

.suggestion-icon {
  width: 32px;
  height: 32px;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--bg-tertiary);
  color: var(--text-secondary);
  flex-shrink: 0;
}

.suggestion-text {
  font-size: 14px;
  color: var(--text-secondary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.model-status {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 8px;
}

.status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  background-color: var(--error-color);
}

.status-dot.status-active {
  background-color: var(--success-color);
  animation: pulse 2s ease-in-out infinite;
}

.status-text {
  font-size: 12px;
  color: var(--text-tertiary);
}

.features-bar {
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 32px;
  padding: 24px;
  border-top: 1px solid var(--border-color);
  background-color: var(--bg-secondary);
  position: relative;
  z-index: 10;
}

.feature-item {
  display: flex;
  align-items: center;
  gap: 8px;
  color: var(--text-tertiary);
}

.feature-item span {
  font-size: 12px;
}

@media (max-width: 640px) {
  .suggestions-grid {
    grid-template-columns: 1fr;
  }
  
  .features-bar {
    flex-wrap: wrap;
    gap: 16px;
  }
  
  .feature-item span {
    display: none;
  }
}
</style>
