// src/components/ConfirmDialog.tsx
import { AlertTriangle, X } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface ConfirmDialogProps {
  isOpen: boolean;
  title: string;
  message: string;
  confirmText?: string;
  cancelText?: string;
  onConfirm: () => void;
  onCancel: () => void;
}

export function ConfirmDialog({
  isOpen,
  title,
  message,
  confirmText = '确认',
  cancelText = '取消',
  onConfirm,
  onCancel,
}: ConfirmDialogProps) {
  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-50 flex items-center justify-center p-4"
          style={{ backgroundColor: 'rgba(0, 0, 0, 0.5)' }}
          onClick={onCancel}
        >
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            exit={{ scale: 0.9, opacity: 0 }}
            className="w-full max-w-sm rounded-xl shadow-2xl overflow-hidden"
            style={{ backgroundColor: 'var(--bg-primary)', border: '1px solid var(--border-color)' }}
            onClick={(e) => e.stopPropagation()}
          >
            <div
              className="flex items-center justify-between px-5 py-4 border-b"
              style={{ borderColor: 'var(--border-color)' }}
            >
              <div className="flex items-center gap-3">
                <div
                  className="flex h-9 w-9 items-center justify-center rounded-lg"
                  style={{ backgroundColor: 'rgba(239, 68, 68, 0.1)' }}
                >
                  <AlertTriangle size={18} style={{ color: 'var(--error-color)' }} />
                </div>
                <h3 className="text-base font-semibold" style={{ color: 'var(--text-primary)' }}>
                  {title}
                </h3>
              </div>
              <button
                onClick={onCancel}
                className="flex h-8 w-8 items-center justify-center rounded-lg transition-colors"
                style={{ color: 'var(--text-tertiary)', backgroundColor: 'var(--bg-secondary)' }}
              >
                <X size={16} />
              </button>
            </div>

            <div className="p-5">
              <p className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                {message}
              </p>
            </div>

            <div
              className="flex items-center justify-end gap-3 px-5 py-4 border-t"
              style={{ borderColor: 'var(--border-color)' }}
            >
              <button
                onClick={onCancel}
                className="rounded-lg px-4 py-2 text-sm font-medium transition-colors"
                style={{
                  color: 'var(--text-primary)',
                  backgroundColor: 'var(--bg-secondary)',
                  border: '1px solid var(--border-color)',
                }}
              >
                {cancelText}
              </button>
              <button
                onClick={onConfirm}
                className="rounded-lg px-4 py-2 text-sm font-medium transition-colors"
                style={{
                  color: 'white',
                  backgroundColor: 'var(--error-color)',
                }}
              >
                {confirmText}
              </button>
            </div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

// 项目重构/src/components/common/ConfirmDialog.vue
<script setup lang="ts">
import { AlertTriangle } from 'lucide-vue-next';

interface Props {
  isOpen: boolean;
  title: string;
  message: string;
  confirmText?: string;
  cancelText?: string;
  type?: 'danger' | 'warning' | 'info';
}

withDefaults(defineProps<Props>(), {
  confirmText: '确认',
  cancelText: '取消',
  type: 'warning',
});

const emit = defineEmits<{
  confirm: [];
  cancel: [];
}>();
</script>

<template>
  <Transition name="modal">
    <div v-if="isOpen" class="confirm-dialog-overlay" @click="emit('cancel')">
      <div class="confirm-dialog" @click.stop>
        <div class="dialog-icon" :class="`is-${type}`">
          <AlertTriangle :size="24" />
        </div>

        <h3 class="dialog-title">{{ title }}</h3>
        <p class="dialog-message">{{ message }}</p>

        <div class="dialog-actions">
          <button class="btn-cancel" @click="emit('cancel')">
            {{ cancelText }}
          </button>
          <button class="btn-confirm" :class="`is-${type}`" @click="emit('confirm')">
            {{ confirmText }}
          </button>
        </div>
      </div>
    </div>
  </Transition>
</template>

<style scoped>
.confirm-dialog-overlay {
  position: fixed;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba(0, 0, 0, 0.5);
  backdrop-filter: blur(4px);
  z-index: 1000;
}

.confirm-dialog {
  width: 90%;
  max-width: 400px;
  background-color: var(--bg-primary);
  border-radius: 16px;
  padding: 24px;
  box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
}

.dialog-icon {
  width: 48px;
  height: 48px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  margin: 0 auto 16px;
}

.dialog-icon.is-danger {
  background-color: rgba(239, 68, 68, 0.1);
  color: #ef4444;
}

.dialog-icon.is-warning {
  background-color: rgba(245, 158, 11, 0.1);
  color: #f59e0b;
}

.dialog-icon.is-info {
  background-color: rgba(59, 130, 246, 0.1);
  color: #3b82f6;
}

.dialog-title {
  font-size: 18px;
  font-weight: 600;
  color: var(--text-primary);
  text-align: center;
  margin-bottom: 8px;
}

.dialog-message {
  font-size: 14px;
  color: var(--text-secondary);
  text-align: center;
  line-height: 1.6;
  margin-bottom: 24px;
}

.dialog-actions {
  display: flex;
  gap: 12px;
}

.btn-cancel,
.btn-confirm {
  flex: 1;
  padding: 10px 20px;
  border-radius: 8px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s ease;
  border: none;
}

.btn-cancel {
  background-color: var(--bg-secondary);
  color: var(--text-secondary);
}

.btn-cancel:hover {
  background-color: var(--bg-tertiary);
}

.btn-confirm {
  color: white;
}

.btn-confirm.is-danger {
  background-color: #ef4444;
}

.btn-confirm.is-danger:hover {
  background-color: #dc2626;
}

.btn-confirm.is-warning {
  background-color: #f59e0b;
}

.btn-confirm.is-warning:hover {
  background-color: #d97706;
}

.btn-confirm.is-info {
  background-color: #3b82f6;
}

.btn-confirm.is-info:hover {
  background-color: #2563eb;
}

.modal-enter-active,
.modal-leave-active {
  transition: all 0.2s ease;
}

.modal-enter-from,
.modal-leave-to {
  opacity: 0;
}

.modal-enter-from .confirm-dialog,
.modal-leave-to .confirm-dialog {
  transform: scale(0.95);
}
</style>
