// 项目重构/src/components/media/FormatConvert.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted } from 'vue';
import { FileType, Settings, Gauge, Film, Music2, MonitorPlay, Upload, ChevronDown, ChevronRight, Sparkles, Info, AlertCircle, Square, Play, Zap, Image as ImageIcon, Maximize2, X } from 'lucide-vue-next';
import { useFFmpegStore } from '@/stores';
import { ffmpegService } from '@/services';
import { useToast } from '@/composables/useToast';
import type { MediaInfo } from '@/types/ffmpeg';

const videoFormats = ['MP4', 'AVI', 'MKV', 'MOV', 'WebM', 'FLV', 'WMV', 'MPEG', 'TS', '3GP', 'OGV'];
const audioFormats = ['MP3', 'AAC', 'WAV', 'FLAC', 'OGG', 'WMA', 'OPUS', 'AC3', 'AIFF', 'M4A'];
const videoCodecs = ['H.264 (libx264)', 'H.265 (libx265)', 'VP9', 'VP8', 'AV1 (libaom)', 'ProRes', 'MPEG-4', 'copy (不转码)'];
const audioCodecs = ['AAC', 'MP3 (libmp3lame)', 'Opus', 'Vorbis', 'FLAC', 'PCM', 'AC3', 'copy (不转码)'];
const presets = ['ultrafast', 'superfast', 'veryfast', 'faster', 'fast', 'medium', 'slow', 'slower', 'veryslow'];
const pixFmts = ['yuv420p', 'yuv422p', 'yuv444p', 'yuv420p10le', 'rgb24', 'auto'];
const resolutions = ['原始', '3840x2160 (4K)', '2560x1440 (2K)', '1920x1080 (1080p)', '1280x720 (720p)', '854x480 (480p)', '640x360 (360p)', '自定义'];

const ffmpegStore = useFFmpegStore();
const toast = useToast();

const mode = ref('video');
const targetFormat = ref('MP4');
const vCodec = ref('H.264 (libx264)');
const aCodec = ref('AAC');
const preset = ref('medium');
const crf = ref(23);
const resolution = ref('原始');
const fps = ref(30);
const changeFps = ref(false);
const audioBitrate = ref(192);
const sampleRate = ref('44100');
const channels = ref('2');
const pixFmt = ref('yuv420p');
const hwAccel = ref(false);
const twoPass = ref(false);
const fastStart = ref(true);
const inputFiles = ref<InputFile[]>([]);
const mainFileIndex = ref(0);
const customFileName = ref('');
const showFullscreen = ref(false);
const dropZoneKey = ref(0);

interface InputFile {
  file: File;
  path: string;
  name: string;
  size: number;
  mediaInfo?: MediaInfo;
  thumbnail?: string;
}

const formats = computed(() => mode.value === 'video' ? videoFormats : audioFormats);

const mainFile = computed(() => inputFiles.value.length > mainFileIndex.value ? inputFiles.value[mainFileIndex.value] : null);
const hasThumbnail = computed(() => mainFile.value && mainFile.value.thumbnail);

const currentModuleTask = computed(() => {
  return ffmpegStore.tasks.find(t => t.module === 'formatConvert' && ffmpegStore.activeTaskIds.has(t.id));
});
const isCurrentModuleProcessing = computed(() => !!currentModuleTask.value);

const handleFilesSelected = async (files: FileList | null) => {
  if (!files || files.length === 0) return;

  const inputFilesData: InputFile[] = [];
  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    inputFilesData.push({
      file,
      path: (file as any).path || file.name,
      name: file.name,
      size: file.size,
    });
  }

  inputFiles.value = inputFilesData;
  mainFileIndex.value = 0;
  customFileName.value = '';

  await loadMainFileInfo(inputFilesData, 0);
};

const loadMainFileInfo = async (files: InputFile[], index: number) => {
  if (files.length > index && files[index].path) {
    const mediaInfo = await ffmpegService.getMediaInfo(
      ffmpegStore.config.ffprobePath,
      files[index].path
    );
    if (mediaInfo) {
      inputFiles.value = inputFiles.value.map((f, i) => i === index ? { ...f, mediaInfo } : f);
    }
  }
};

const selectMainFile = async (index: number) => {
  mainFileIndex.value = index;
  customFileName.value = '';
  await loadMainFileInfo(inputFiles.value, index);
};

const removeFile = (index: number) => {
  inputFiles.value = inputFiles.value.filter((_, i) => i !== index);
  if (mainFileIndex.value >= inputFiles.value.length) {
    mainFileIndex.value = Math.max(0, inputFiles.value.length - 1);
  }
};

const clearAllFiles = () => {
  inputFiles.value = [];
  mainFileIndex.value = 0;
  customFileName.value = '';
  dropZoneKey.value++;
};

const getOutputFilePath = (inputFile: InputFile, customName?: string): string => {
  const inputPath = inputFile.path;
  const lastSepIndex = Math.max(inputPath.lastIndexOf('/'), inputPath.lastIndexOf('\\'));
  const inputDir = lastSepIndex >= 0 ? inputPath.substring(0, lastSepIndex) : '';
  const lastDotIndex = inputFile.name.lastIndexOf('.');
  const inputName = lastDotIndex >= 0 ? inputFile.name.substring(0, lastDotIndex) : inputFile.name;
  
  const outputDir = inputDir;
  const extension = targetFormat.value.toLowerCase();
  const sep = outputDir.includes('\\') ? '\\' : '/';
  
  const finalName = customName && customName.trim() ? customName.trim() : `${inputName}_converted`;
  
  return outputDir ? `${outputDir}${sep}${finalName}.${extension}` : `${finalName}.${extension}`;
};

const buildConvertArgs = (): string[] => {
  const args: string[] = ['-i', mainFile.value!.path];
  
  const vCodecMap: Record<string, string> = {
    'H.264 (libx264)': 'libx264',
    'H.265 (libx265)': 'libx265',
    'VP9': 'libvpx-vp9',
    'VP8': 'libvpx',
    'AV1 (libaom)': 'libaom-av1',
    'ProRes': 'prores_ks',
    'MPEG-4': 'mpeg4',
    'copy (不转码)': 'copy',
  };
  
  const aCodecMap: Record<string, string> = {
    'AAC': 'aac',
    'MP3 (libmp3lame)': 'libmp3lame',
    'Opus': 'libopus',
    'Vorbis': 'libvorbis',
    'FLAC': 'flac',
    'PCM': 'pcm_s16le',
    'AC3': 'ac3',
    'copy (不转码)': 'copy',
  };
  
  const videoCodec = vCodecMap[vCodec.value] || 'libx264';
  const audioCodec = aCodecMap[aCodec.value] || 'aac';
  
  if (videoCodec !== 'copy') {
    args.push('-c:v', videoCodec);
    args.push('-preset', preset.value);
    args.push('-crf', String(crf.value));
    
    if (pixFmt.value !== 'auto') {
      args.push('-pix_fmt', pixFmt.value);
    }
    
    if (resolution.value !== '原始') {
      const resMap: Record<string, string> = {
        '3840x2160 (4K)': '3840:2160',
        '2560x1440 (2K)': '2560:1440',
        '1920x1080 (1080p)': '1920:1080',
        '1280x720 (720p)': '1280:720',
        '854x480 (480p)': '854:480',
        '640x360 (360p)': '640:360',
      };
      if (resMap[resolution.value]) {
        args.push('-vf', `scale=${resMap[resolution.value]}`);
      }
    }
    
    if (changeFps.value) {
      args.push('-r', String(fps.value));
    }
  } else {
    args.push('-c:v', 'copy');
  }
  
  if (audioCodec !== 'copy') {
    args.push('-c:a', audioCodec);
    args.push('-b:a', `${audioBitrate.value}k`);
    args.push('-ar', sampleRate.value);
    args.push('-ac', channels.value);
  } else {
    args.push('-c:a', 'copy');
  }
  
  if (fastStart.value && targetFormat.value.toLowerCase() === 'mp4') {
    args.push('-movflags', '+faststart');
  }
  
  args.push('-y');
  args.push(getOutputFilePath(mainFile.value!, customFileName.value));
  
  return args;
};

const handleStart = async () => {
  if (!ffmpegStore.isConfigured) {
    toast.error('请先在配置中设置 FFmpeg bin 目录');
    return;
  }

  if (inputFiles.value.length === 0 || !mainFile.value) {
    toast.warning('请先选择要转换的文件');
    return;
  }

  const outputFilePath = getOutputFilePath(mainFile.value!, customFileName.value);
  const taskId = ffmpegStore.addTask({
    fileName: mainFile.value!.name,
    module: 'formatConvert',
    status: 'processing',
    progress: 0,
    inputPath: mainFile.value!.path,
    outputPath: outputFilePath,
  });

  ffmpegStore.addTaskLog(taskId, '[info] FFmpeg Studio v1.0 - 格式转换模块');
  ffmpegStore.addTaskLog(taskId, `[info] 目标格式: ${targetFormat.value}`);
  ffmpegStore.addTaskLog(taskId, `[info] 视频编码: ${vCodec.value} | 音频编码: ${aCodec.value}`);
  ffmpegStore.addTaskLog(taskId, `[info] 预设: ${preset.value} | CRF: ${crf.value}`);

  try {
    const args = buildConvertArgs();
    const duration = mainFile.value!.mediaInfo?.duration;
    
    const result = await ffmpegService.executeWithProgress({
      ffmpegPath: ffmpegStore.config.ffmpegPath,
      args,
      taskId,
      duration,
    });

    ffmpegStore.updateTask(taskId, {
      status: result.success ? 'completed' : 'error',
      progress: 100,
      error: result.error,
    });

    if (result.success) {
      ffmpegStore.addTaskLog(taskId, '[done] 转换完成');
    } else {
      ffmpegStore.addTaskLog(taskId, `[error] 转换失败: ${result.error}`);
    }
  } catch (error) {
    ffmpegStore.updateTask(taskId, {
      status: 'error',
      error: error instanceof Error ? error.message : '未知错误',
    });
    ffmpegStore.addTaskLog(taskId, `[error] 转换失败: ${error}`);
  }
};

const handleStop = async () => {
  if (currentModuleTask.value) {
    await ffmpegService.stop();
    ffmpegStore.stopTask(currentModuleTask.value.id);
  }
};
</script>

<template>
  <div class="format-convert">
    <div class="header">
      <div class="title-row">
        <FileType :size="20" class="icon" />
        <h2>格式转换</h2>
        <span class="badge blue">全格式</span>
        <span v-if="isCurrentModuleProcessing" class="badge green">
          <span class="pulse-dot" />处理中
        </span>
      </div>
      <div class="mode-tabs">
        <button 
          :class="['mode-tab', { active: mode === 'video' }]"
          @click="mode = 'video'"
        >
          <Film :size="14" />
          <span>视频转换</span>
        </button>
        <button 
          :class="['mode-tab', { active: mode === 'audio' }]"
          @click="mode = 'audio'"
        >
          <Music2 :size="14" />
          <span>音频转换</span>
        </button>
      </div>
    </div>

    <div v-if="!ffmpegStore.isConfigured" class="warning-banner">
      <AlertCircle :size="16" />
      <span>请先在配置中设置 FFmpeg bin 目录</span>
    </div>

    <div class="content-grid">
      <div class="left-panel">
        <div v-if="inputFiles.length > 0" class="card">
          <div class="card-header">
            <FileType :size="16" class="icon" />
            <span class="card-title">文件列表</span>
            <span class="file-count">{{ inputFiles.length }}</span>
            <button class="btn-clear" @click="clearAllFiles">清空</button>
          </div>
          <div class="file-list">
            <div 
              v-for="(file, index) in inputFiles" 
              :key="index"
              :class="['file-item', { active: mainFileIndex === index }]"
              @click="selectMainFile(index)"
            >
              <Sparkles v-if="mainFileIndex === index" :size="12" class="star-icon" />
              <span class="file-name">{{ file.name }}</span>
              <span class="file-size">{{ (file.size / 1024 / 1024).toFixed(1) }}MB</span>
            </div>
          </div>
          <div class="file-hint">点击文件可设为主文件</div>
        </div>

        <div class="card">
          <div class="card-header">
            <Upload :size="16" class="icon" />
            <span class="card-title">文件导入</span>
          </div>
          <label :key="dropZoneKey" class="drop-zone">
            <input 
              type="file" 
              :accept="mode === 'video' ? 'video/*' : 'audio/*'"
              multiple
              @change="handleFilesSelected"
            />
            <div class="drop-zone-content">
              <Upload :size="32" class="upload-icon" />
              <p>{{ mode === 'video' ? '拖拽视频文件' : '拖拽音频文件' }}</p>
              <p class="hint">或点击选择文件</p>
            </div>
          </label>
        </div>

        <div class="card">
          <div class="card-header">
            <FileType :size="16" class="icon" />
            <span class="card-title">输出文件名</span>
          </div>
          <div class="filename-input">
            <input 
              type="text" 
              v-model="customFileName"
              placeholder="留空则使用默认名称"
            />
            <span class="extension">.{{ targetFormat.toLowerCase() }}</span>
          </div>
        </div>

        <div class="card">
          <div class="card-header">
            <FileType :size="16" class="icon" />
            <span class="card-title">输出格式</span>
          </div>
          <div class="format-grid">
            <button 
              v-for="format in formats" 
              :key="format"
              :class="['format-btn', { active: targetFormat === format }]"
              @click="targetFormat = format"
            >
              {{ format }}
            </button>
          </div>
        </div>
      </div>

      <div class="right-panel">
        <div v-if="mainFile" class="main-file-card">
          <div class="main-file-info">
            <div class="info-header">
              <Sparkles :size="16" class="icon" />
              <span>主文件</span>
            </div>
            <div class="info-content">
              <span class="file-name">{{ mainFile.name }}</span>
              <div class="file-details">
                <span>{{ (mainFile.size / 1024 / 1024).toFixed(1) }} MB</span>
                <template v-if="mainFile.mediaInfo?.video">
                  <span>{{ mainFile.mediaInfo.video.codec }}</span>
                  <span>{{ mainFile.mediaInfo.video.fps?.toFixed(1) }} fps</span>
                  <span>{{ mainFile.mediaInfo.duration?.toFixed(1) }}s</span>
                </template>
              </div>
            </div>
          </div>
        </div>

        <div :class="['action-card', { processing: isCurrentModuleProcessing }]">
          <div class="action-row">
            <button 
              :disabled="!ffmpegStore.isConfigured"
              :class="['action-btn', { stop: isCurrentModuleProcessing }]"
              @click="isCurrentModuleProcessing ? handleStop() : handleStart()"
            >
              <Square v-if="isCurrentModuleProcessing" :size="16" />
              <Play v-else :size="16" />
              <span>{{ isCurrentModuleProcessing ? '停止转换' : '开始转换' }}</span>
            </button>
            <div v-if="isCurrentModuleProcessing && currentModuleTask" class="progress-info">
              <div class="progress-bar">
                <div class="progress-fill" :style="{ width: `${currentModuleTask.progress}%` }" />
              </div>
              <span class="progress-text">{{ Math.floor(currentModuleTask.progress) }}%</span>
            </div>
            <div v-else class="hint-text">
              <Info :size="14" />
              <span>选择文件后点击开始转换</span>
            </div>
          </div>
        </div>

        <div class="card">
          <div class="card-header">
            <Zap :size="16" class="icon warning" />
            <span class="card-title">快速预设</span>
          </div>
          <div class="preset-grid">
            <button 
              v-for="p in [
                { name: '高质量', desc: '大文件，最佳画质', crf: 18, preset: 'slow' },
                { name: '均衡', desc: '画质体积平衡', crf: 23, preset: 'medium' },
                { name: '压缩', desc: '小文件，较快速度', crf: 28, preset: 'fast' },
                { name: '极速', desc: '最快速度，较大文件', crf: 23, preset: 'ultrafast' },
              ]"
              :key="p.name"
              :class="['preset-btn', { active: crf === p.crf && preset === p.preset }]"
              @click="crf = p.crf; preset = p.preset"
            >
              <div class="preset-name">{{ p.name }}</div>
              <div class="preset-desc">{{ p.desc }}</div>
            </button>
          </div>
        </div>

        <div class="card collapsible">
          <div class="card-header clickable">
            <Settings :size="16" class="icon" />
            <span class="card-title">编码设置</span>
            <ChevronDown :size="16" class="chevron" />
          </div>
          <div class="card-body">
            <div class="form-grid">
              <div class="form-group">
                <label>视频编码器</label>
                <select v-model="vCodec">
                  <option v-for="c in videoCodecs" :key="c">{{ c }}</option>
                </select>
              </div>
              <div class="form-group">
                <label>音频编码器</label>
                <select v-model="aCodec">
                  <option v-for="c in audioCodecs" :key="c">{{ c }}</option>
                </select>
              </div>
              <div class="form-group">
                <label>编码预设</label>
                <select v-model="preset">
                  <option v-for="p in presets" :key="p">{{ p }}</option>
                </select>
              </div>
            </div>
            <div class="form-grid">
              <div class="form-group slider">
                <label>CRF (质量): {{ crf }}</label>
                <input type="range" v-model="crf" min="0" max="51" />
              </div>
              <div class="form-group">
                <label>像素格式</label>
                <select v-model="pixFmt">
                  <option v-for="p in pixFmts" :key="p">{{ p }}</option>
                </select>
              </div>
            </div>
          </div>
        </div>

        <div v-if="mode === 'video'" class="card collapsible">
          <div class="card-header clickable">
            <MonitorPlay :size="16" class="icon" />
            <span class="card-title">视频参数</span>
            <ChevronDown :size="16" class="chevron" />
          </div>
          <div class="card-body">
            <div class="form-grid">
              <div class="form-group">
                <label>分辨率</label>
                <select v-model="resolution">
                  <option v-for="r in resolutions" :key="r">{{ r }}</option>
                </select>
              </div>
              <div class="form-group checkbox">
                <label>
                  <input type="checkbox" v-model="changeFps" />
                  修改帧率
                </label>
                <div v-if="changeFps" class="fps-slider">
                  <label>帧率: {{ fps }} fps</label>
                  <input type="range" v-model="fps" min="1" max="120" />
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="card collapsible">
          <div class="card-header clickable">
            <Music2 :size="16" class="icon" />
            <span class="card-title">音频参数</span>
            <ChevronDown :size="16" class="chevron" />
          </div>
          <div class="card-body">
            <div class="form-grid">
              <div class="form-group slider">
                <label>比特率: {{ audioBitrate }} kbps</label>
                <input type="range" v-model="audioBitrate" min="64" max="512" />
              </div>
              <div class="form-group">
                <label>采样率</label>
                <select v-model="sampleRate">
                  <option v-for="s in ['8000', '16000', '22050', '44100', '48000', '96000']" :key="s">{{ s }} Hz</option>
                </select>
              </div>
              <div class="form-group">
                <label>声道</label>
                <select v-model="channels">
                  <option value="1">单声道</option>
                  <option value="2">立体声</option>
                  <option value="6">5.1 环绕声</option>
                  <option value="8">7.1 环绕声</option>
                </select>
              </div>
            </div>
          </div>
        </div>

        <div class="card collapsible">
          <div class="card-header clickable">
            <Gauge :size="16" class="icon" />
            <span class="card-title">高级选项</span>
            <ChevronDown :size="16" class="chevron" />
          </div>
          <div class="card-body">
            <div class="form-grid checkboxes">
              <label class="checkbox-label">
                <input type="checkbox" v-model="hwAccel" />
                硬件加速 (NVENC/QSV/AMF)
              </label>
              <label class="checkbox-label">
                <input type="checkbox" v-model="twoPass" />
                二次编码 (Two-Pass)
              </label>
              <label class="checkbox-label">
                <input type="checkbox" v-model="fastStart" />
                快速启动 (moov前移)
              </label>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.format-convert {
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 16px;
  padding: 16px;
}

.header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-shrink: 0;
}

.title-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.icon {
  color: var(--primary-color);
}

.icon.warning {
  color: var(--warning-color);
}

h2 {
  font-size: 18px;
  font-weight: 700;
  color: var(--text-primary);
  margin: 0;
}

.badge {
  font-size: 10px;
  padding: 2px 8px;
  border-radius: 9999px;
}

.badge.blue {
  background-color: rgba(59, 130, 246, 0.15);
  color: var(--primary-color);
}

.badge.green {
  background-color: rgba(16, 185, 129, 0.15);
  color: #10b981;
  display: flex;
  align-items: center;
  gap: 4px;
}

.pulse-dot {
  width: 6px;
  height: 6px;
  border-radius: 50%;
  background-color: #10b981;
  animation: pulse 2s infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.5; }
}

.mode-tabs {
  display: flex;
  gap: 4px;
}

.mode-tab {
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 12px;
  border-radius: 8px;
  border: none;
  background: transparent;
  color: var(--text-tertiary);
  font-size: 12px;
  cursor: pointer;
  transition: all 0.2s;
}

.mode-tab:hover {
  background-color: var(--hover-bg);
}

.mode-tab.active {
  background-color: var(--primary-light);
  color: var(--primary-color);
}

.warning-banner {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 16px;
  border-radius: 12px;
  background-color: rgba(239, 68, 68, 0.1);
  border: 1px solid rgba(239, 68, 68, 0.3);
  color: #ef4444;
  font-size: 12px;
  flex-shrink: 0;
}

.content-grid {
  flex: 1;
  display: grid;
  grid-template-columns: 1fr 2fr;
  gap: 16px;
  min-height: 0;
  overflow: hidden;
}

.left-panel,
.right-panel {
  display: flex;
  flex-direction: column;
  gap: 16px;
  overflow-y: auto;
  padding-right: 8px;
}

.card {
  background-color: var(--bg-secondary);
  border: 1px solid var(--border-color);
  border-radius: 12px;
  overflow: hidden;
}

.card-header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 12px 16px;
  border-bottom: 1px solid var(--border-color);
}

.card-header.clickable {
  cursor: pointer;
}

.card-header.clickable:hover {
  background-color: var(--hover-bg);
}

.card-title {
  font-size: 14px;
  font-weight: 500;
  color: var(--text-primary);
}

.file-count {
  font-size: 10px;
  padding: 2px 6px;
  border-radius: 9999px;
  background-color: var(--primary-light);
  color: var(--primary-color);
}

.btn-clear {
  margin-left: auto;
  font-size: 10px;
  padding: 4px 8px;
  border-radius: 6px;
  border: none;
  background-color: rgba(239, 68, 68, 0.15);
  color: #ef4444;
  cursor: pointer;
  transition: all 0.2s;
}

.btn-clear:hover {
  transform: scale(1.05);
}

.file-list {
  padding: 8px;
  max-height: 200px;
  overflow-y: auto;
}

.file-item {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 8px 12px;
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s;
  margin-bottom: 4px;
}

.file-item:hover {
  background-color: var(--hover-bg);
}

.file-item.active {
  background-color: var(--primary-light);
  border: 1px solid var(--primary-color);
}

.star-icon {
  color: var(--primary-color);
}

.file-name {
  flex: 1;
  font-size: 12px;
  color: var(--text-primary);
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.file-size {
  font-size: 10px;
  color: var(--text-tertiary);
  white-space: nowrap;
}

.file-hint {
  padding: 8px 16px;
  font-size: 11px;
  color: var(--text-tertiary);
}

.drop-zone {
  display: block;
  padding: 24px;
  border: 2px dashed var(--border-color);
  border-radius: 8px;
  cursor: pointer;
  transition: all 0.2s;
}

.drop-zone:hover {
  border-color: var(--primary-color);
  background-color: var(--primary-light);
}

.drop-zone input {
  display: none;
}

.drop-zone-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  color: var(--text-tertiary);
}

.upload-icon {
  opacity: 0.5;
}

.drop-zone-content p {
  font-size: 12px;
  margin: 0;
}

.drop-zone-content .hint {
  font-size: 10px;
}

.filename-input {
  display: flex;
  gap: 8px;
  padding: 12px 16px;
}

.filename-input input {
  flex: 1;
  padding: 8px 12px;
  border-radius: 8px;
  border: 1px solid var(--border-color);
  background-color: var(--bg-primary);
  color: var(--text-primary);
  font-size: 12px;
  outline: none;
}

.filename-input input:focus {
  border-color: var(--primary-color);
}

.extension {
  padding: 8px 12px;
  border-radius: 8px;
  background-color: var(--bg-tertiary);
  color: var(--text-tertiary);
  font-size: 12px;
}

.format-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 4px;
  padding: 12px 16px;
}

.format-btn {
  padding: 6px 8px;
  border-radius: 6px;
  border: 1px solid transparent;
  background-color: var(--bg-tertiary);
  color: var(--text-secondary);
  font-size: 12px;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
}

.format-btn:hover {
  transform: scale(1.05);
}

.format-btn.active {
  background-color: var(--primary-light);
  border-color: var(--primary-color);
  color: var(--primary-color);
}

.main-file-card {
  background-color: var(--bg-secondary);
  border: 1px solid var(--primary-color);
  border-radius: 12px;
  overflow: hidden;
}

.main-file-info {
  padding: 16px;
}

.info-header {
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 12px;
}

.info-header .icon {
  color: var(--primary-color);
}

.info-header span {
  font-size: 14px;
  font-weight: 500;
  color: var(--text-primary);
}

.info-content .file-name {
  font-size: 12px;
  color: var(--text-primary);
  display: block;
  margin-bottom: 8px;
}

.file-details {
  display: flex;
  gap: 16px;
  font-size: 11px;
  color: var(--text-tertiary);
}

.action-card {
  background-color: var(--bg-secondary);
  border: 1px solid var(--border-color);
  border-radius: 12px;
  padding: 16px;
  transition: all 0.3s;
}

.action-card.processing {
  background-color: rgba(6, 182, 212, 0.1);
  border-color: #06b6d4;
}

.action-row {
  display: flex;
  align-items: center;
  gap: 16px;
}

.action-btn {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 24px;
  border-radius: 8px;
  border: none;
  background: linear-gradient(135deg, #0891b2, #06b6d4);
  color: white;
  font-size: 14px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
  box-shadow: 0 4px 15px rgba(6, 182, 212, 0.3);
}

.action-btn:hover:not(:disabled) {
  transform: scale(1.05);
}

.action-btn:disabled {
  opacity: 0.5;
  cursor: not-allowed;
}

.action-btn.stop {
  background: linear-gradient(135deg, #ef4444, #dc2626);
  box-shadow: 0 4px 15px rgba(239, 68, 68, 0.4);
}

.progress-info {
  flex: 1;
  display: flex;
  align-items: center;
  gap: 12px;
}

.progress-bar {
  flex: 1;
  height: 8px;
  border-radius: 4px;
  background-color: var(--bg-tertiary);
  overflow: hidden;
}

.progress-fill {
  height: 100%;
  background: linear-gradient(90deg, #06b6d4, #0891b2);
  transition: width 0.3s;
}

.progress-text {
  font-size: 12px;
  color: var(--text-tertiary);
  min-width: 40px;
}

.hint-text {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  color: var(--text-tertiary);
}

.preset-grid {
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 8px;
  padding: 12px 16px;
}

.preset-btn {
  padding: 12px;
  border-radius: 8px;
  border: 1px solid transparent;
  background-color: var(--bg-tertiary);
  cursor: pointer;
  transition: all 0.2s;
  text-align: left;
}

.preset-btn:hover {
  transform: scale(1.05);
}

.preset-btn.active {
  background-color: var(--primary-light);
  border-color: var(--primary-color);
}

.preset-name {
  font-size: 12px;
  font-weight: 500;
  color: var(--text-primary);
}

.preset-btn.active .preset-name {
  color: var(--primary-color);
}

.preset-desc {
  font-size: 10px;
  color: var(--text-tertiary);
  margin-top: 2px;
}

.card-body {
  padding: 16px;
}

.form-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 16px;
  margin-bottom: 16px;
}

.form-grid:last-child {
  margin-bottom: 0;
}

.form-grid.checkboxes {
  grid-template-columns: repeat(3, 1fr);
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.form-group label {
  font-size: 12px;
  color: var(--text-secondary);
}

.form-group select,
.form-group input[type="text"] {
  padding: 8px 12px;
  border-radius: 8px;
  border: 1px solid var(--border-color);
  background-color: var(--bg-primary);
  color: var(--text-primary);
  font-size: 12px;
  outline: none;
}

.form-group select:focus,
.form-group input[type="text"]:focus {
  border-color: var(--primary-color);
}

.form-group.slider input[type="range"] {
  width: 100%;
}

.checkbox-label {
  display: flex;
  align-items: center;
  gap: 8px;
  font-size: 12px;
  color: var(--text-secondary);
  cursor: pointer;
}

.checkbox-label input {
  width: 16px;
  height: 16px;
}

.chevron {
  margin-left: auto;
  color: var(--text-tertiary);
}
</style>

// src/pages/MediaTools/FormatConvert.tsx
import { useState, useEffect, useCallback } from 'react';
import { 
  FileType, Settings, Gauge, Film, Music2, MonitorPlay, 
  Upload, ChevronDown, ChevronRight, Sparkles, Zap, Info,
  AlertCircle, Square
} from 'lucide-react';
import { SectionCard, FileDropZone, FormRow, Toggle, Slider, Tabs, ProgressBar, Terminal, Badge } from '@/components/ffmpeg';
import { motion, AnimatePresence } from 'framer-motion';
import { ffmpegRendererService, type MediaInfo } from '@/services/ffmpeg/FFmpegRendererService';
import { useFFmpegStore } from '@/stores/ffmpegStore';
import { useToast } from '@/components/Toast';

const videoFormats = ['MP4', 'AVI', 'MKV', 'MOV', 'WebM', 'FLV', 'WMV', 'MPEG', 'TS', '3GP', 'OGV'];
const audioFormats = ['MP3', 'AAC', 'WAV', 'FLAC', 'OGG', 'WMA', 'OPUS', 'AC3', 'AIFF', 'M4A'];
const videoCodecs = ['H.264 (libx264)', 'H.265 (libx265)', 'VP9', 'VP8', 'AV1 (libaom)', 'ProRes', 'MPEG-4', 'copy (不转码)'];
const audioCodecs = ['AAC', 'MP3 (libmp3lame)', 'Opus', 'Vorbis', 'FLAC', 'PCM', 'AC3', 'copy (不转码)'];
const presets = ['ultrafast', 'superfast', 'veryfast', 'faster', 'fast', 'medium', 'slow', 'slower', 'veryslow'];
const pixFmts = ['yuv420p', 'yuv422p', 'yuv444p', 'yuv420p10le', 'rgb24', 'auto'];
const resolutions = ['原始', '3840x2160 (4K)', '2560x1440 (2K)', '1920x1080 (1080p)', '1280x720 (720p)', '854x480 (480p)', '640x360 (360p)', '自定义'];

interface InputFile {
  file: File;
  path: string;
  name: string;
  size: number;
  mediaInfo?: MediaInfo;
}

interface CollapsibleSectionProps {
  title: string;
  icon: React.ReactNode;
  children: React.ReactNode;
  defaultOpen?: boolean;
}

function CollapsibleSection({ title, icon, children, defaultOpen = true }: CollapsibleSectionProps) {
  const [isOpen, setIsOpen] = useState(defaultOpen);
  
  return (
    <div 
      className="rounded-xl overflow-hidden"
      style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}
    >
      <button
        onClick={() => setIsOpen(!isOpen)}
        className="w-full flex items-center justify-between px-4 py-3 transition-colors"
        style={{ backgroundColor: isOpen ? 'var(--bg-tertiary)' : 'transparent' }}
      >
        <div className="flex items-center gap-2">
          <span style={{ color: 'var(--primary-color)' }}>{icon}</span>
          <span className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>{title}</span>
        </div>
        {isOpen ? <ChevronDown className="w-4 h-4" style={{ color: 'var(--text-tertiary)' }} /> : <ChevronRight className="w-4 h-4" style={{ color: 'var(--text-tertiary)' }} />}
      </button>
      <AnimatePresence>
        {isOpen && (
          <motion.div
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: 'auto', opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.2 }}
            className="overflow-hidden"
          >
            <div className="p-4 space-y-3">
              {children}
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

export function FormatConvert() {
  const [mode, setMode] = useState('video');
  const [targetFormat, setTargetFormat] = useState('MP4');
  const [vCodec, setVCodec] = useState('H.264 (libx264)');
  const [aCodec, setACodec] = useState('AAC');
  const [preset, setPreset] = useState('medium');
  const [crf, setCrf] = useState(23);
  const [resolution, setResolution] = useState('原始');
  const [fps, setFps] = useState(30);
  const [changeFps, setChangeFps] = useState(false);
  const [audioBitrate, setAudioBitrate] = useState(192);
  const [sampleRate, setSampleRate] = useState('44100');
  const [channels, setChannels] = useState('2');
  const [pixFmt, setPixFmt] = useState('yuv420p');
  const [hwAccel, setHwAccel] = useState(false);
  const [twoPass, setTwoPass] = useState(false);
  const [fastStart, setFastStart] = useState(true);
  const [inputFiles, setInputFiles] = useState<InputFile[]>([]);
  const [customFileName, setCustomFileName] = useState('');
  
  const { 
    isConfigured, 
    isElectronEnv, 
    outputPath, 
    tasks,
    activeTaskIds,
    checkConfig, 
    startTask, 
    completeTask, 
    stopTask,
    addTaskLog,
    generateUniquePath,
  } = useFFmpegStore();
  
  const toast = useToast();

  const formats = mode === 'video' ? videoFormats : audioFormats;

  useEffect(() => {
    checkConfig();
  }, [checkConfig]);

  const handleFilesSelected = useCallback(async (files: File[]) => {
    if (files.length === 0) return;

    const inputFilesData: InputFile[] = files.map(file => ({
      file,
      path: (file as any).path || file.name,
      name: file.name,
      size: file.size,
    }));

    setInputFiles(inputFilesData);
    setCustomFileName('');

    if (inputFilesData.length > 0 && inputFilesData[0].path) {
      const mediaInfo = await ffmpegRendererService.getMediaInfo(inputFilesData[0].path);
      if (mediaInfo) {
        setInputFiles(prev => prev.map((f, i) => i === 0 ? { ...f, mediaInfo } : f));
      }
    }
  }, []);

  const getOutputFilePath = (inputFile: InputFile, customName?: string): string => {
    const inputPath = inputFile.path;
    const lastSepIndex = Math.max(inputPath.lastIndexOf('/'), inputPath.lastIndexOf('\\'));
    const inputDir = lastSepIndex >= 0 ? inputPath.substring(0, lastSepIndex) : '';
    const lastDotIndex = inputFile.name.lastIndexOf('.');
    const inputName = lastDotIndex >= 0 ? inputFile.name.substring(0, lastDotIndex) : inputFile.name;
    
    const outputDir = outputPath || inputDir;
    const extension = targetFormat.toLowerCase();
    const sep = outputDir.includes('\\') ? '\\' : '/';
    
    const finalName = customName && customName.trim() ? customName.trim() : `${inputName}_converted`;
    
    return outputDir ? `${outputDir}${sep}${finalName}.${extension}` : `${finalName}.${extension}`;
  };

  const handleStart = async () => {
    if (!isElectronEnv) {
      toast.error('请使用 Electron 模式运行此功能（运行 npm run electron:dev）');
      return;
    }

    if (!isConfigured) {
      toast.error('请先在配置中设置 FFmpeg bin 目录');
      return;
    }

    if (inputFiles.length === 0) {
      toast.error('请先选择要转换的文件');
      return;
    }

    const inputFile = inputFiles[0];
    const baseOutputPath = getOutputFilePath(inputFile, customFileName);
    const outputFilePath = generateUniquePath(baseOutputPath);
    const taskId = startTask('formatConvert', inputFile.name, inputFile.path, outputFilePath);

    addTaskLog(taskId, '[info] FFmpeg Studio v1.0 - 格式转换模块');
    addTaskLog(taskId, `[info] 目标格式: ${targetFormat}`);
    addTaskLog(taskId, `[info] 视频编码: ${vCodec} | 音频编码: ${aCodec}`);
    addTaskLog(taskId, `[info] 预设: ${preset} | CRF: ${crf}`);
    addTaskLog(taskId, `[info] 分辨率: ${resolution} | 像素格式: ${pixFmt}`);
    if (hwAccel) addTaskLog(taskId, '[info] 硬件加速: 已启用 (NVENC/QSV)');
    if (twoPass) addTaskLog(taskId, '[info] 二次编码: 已启用');

    try {
      const args = ffmpegRendererService.buildConvertArgs(
        inputFile.path,
        outputFilePath,
        {
          videoCodec: vCodec,
          audioCodec: aCodec,
          preset,
          crf,
          resolution,
          fps: changeFps ? fps : undefined,
          audioBitrate,
          sampleRate,
          channels,
          pixFmt,
          hwAccel,
          twoPass,
          fastStart,
        }
      );

      const duration = inputFile.mediaInfo?.duration;
      const result = await ffmpegRendererService.executeWithProgress(args, duration, taskId);

      completeTask(taskId, result.success, result.error);
      if (result.success) {
        toast.success('转换完成！');
      } else {
        toast.error('转换失败');
      }
    } catch (error) {
      completeTask(taskId, false, error instanceof Error ? error.message : '未知错误');
      toast.error('转换失败');
    }
  };

  const handleStop = async () => {
    const moduleTasks = tasks.filter(t => t.module === 'formatConvert' && activeTaskIds.has(t.id));
    if (moduleTasks.length > 0) {
      await stopTask(moduleTasks[0].id);
      toast.info('已停止处理');
    }
  };

  const currentModuleTask = tasks.find(t => t.module === 'formatConvert' && activeTaskIds.has(t.id));
  const isCurrentModuleProcessing = !!currentModuleTask;

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileType className="w-5 h-5" style={{ color: 'var(--primary-color)' }} />
          <h2 className="text-lg font-bold" style={{ color: 'var(--text-primary)' }}>格式转换</h2>
          <Badge color="blue">全格式</Badge>
          {isCurrentModuleProcessing && (
            <Badge color="green">
              <span className="flex items-center gap-1">
                <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                处理中
              </span>
            </Badge>
          )}
        </div>
        <Tabs
          tabs={[
            { key: 'video', label: '视频转换', icon: <Film className="w-3.5 h-3.5" /> },
            { key: 'audio', label: '音频转换', icon: <Music2 className="w-3.5 h-3.5" /> },
          ]}
          active={mode}
          onChange={setMode}
        />
      </div>

      {!isElectronEnv && (
        <div 
          className="flex items-center gap-2 px-4 py-3 rounded-xl"
          style={{ backgroundColor: 'rgba(234, 179, 8, 0.1)', border: '1px solid rgba(234, 179, 8, 0.3)' }}
        >
          <AlertCircle className="w-4 h-4 text-yellow-500" />
          <span className="text-xs text-yellow-600">请使用 Electron 模式运行此功能（运行 <code className="px-1 py-0.5 rounded bg-yellow-100">npm run electron:dev</code>）</span>
        </div>
      )}

      {isElectronEnv && !isConfigured && (
        <div 
          className="flex items-center gap-2 px-4 py-3 rounded-xl"
          style={{ backgroundColor: 'rgba(239, 68, 68, 0.1)', border: '1px solid rgba(239, 68, 68, 0.3)' }}
        >
          <AlertCircle className="w-4 h-4 text-red-500" />
          <span className="text-xs text-red-600">请先在右上角配置按钮中设置 FFmpeg bin 目录</span>
        </div>
      )}

      <div className="grid grid-cols-12 gap-4">
        <div className="col-span-4 space-y-4">
          <div 
            className="rounded-xl p-4"
            style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}
          >
            <div className="flex items-center gap-2 mb-4">
              <Upload className="w-4 h-4" style={{ color: 'var(--primary-color)' }} />
              <span className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>输入文件</span>
            </div>
            <FileDropZone
              accept={mode === 'video' ? 'video/*' : 'audio/*'}
              multiple
              label={mode === 'video' ? '拖拽视频文件' : '拖拽音频文件'}
              onFiles={handleFilesSelected}
            />
            {inputFiles.length > 0 && (
              <div className="mt-3 space-y-2">
                {inputFiles.map((f, i) => (
                  <div key={i} className="flex items-center gap-2 px-3 py-2 rounded-lg" style={{ backgroundColor: 'var(--bg-tertiary)' }}>
                    <span className="flex-1 truncate text-xs" style={{ color: 'var(--text-primary)' }}>{f.name}</span>
                    <span className="text-xs" style={{ color: 'var(--text-tertiary)' }}>{(f.size / 1024 / 1024).toFixed(1)} MB</span>
                  </div>
                ))}
              </div>
            )}
          </div>

          <div 
            className="rounded-xl p-4"
            style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}
          >
            <div className="flex items-center gap-2 mb-3">
              <FileType className="w-4 h-4" style={{ color: 'var(--primary-color)' }} />
              <span className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>输出文件名</span>
            </div>
            <div className="flex items-center gap-2">
              <input
                type="text"
                className="flex-1 rounded-lg px-3 py-2 text-xs outline-none"
                style={{ backgroundColor: 'var(--bg-primary)', border: '1px solid var(--border-color)', color: 'var(--text-primary)' }}
                placeholder="留空则使用默认名称（原文件名_converted）"
                value={customFileName}
                onChange={(e) => setCustomFileName(e.target.value)}
              />
              <span 
                className="px-3 py-2 rounded-lg text-xs"
                style={{ backgroundColor: 'var(--bg-tertiary)', color: 'var(--text-tertiary)' }}
              >
                .{targetFormat.toLowerCase()}
              </span>
            </div>
            {customFileName && customFileName.trim() && inputFiles.length > 0 && (
              <div className="mt-2 text-xs" style={{ color: 'var(--text-tertiary)' }}>
                预览: {customFileName.trim()}.{targetFormat.toLowerCase()}
              </div>
            )}
          </div>

          <div 
            className="rounded-xl p-4"
            style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}
          >
            <div className="flex items-center gap-2 mb-3">
              <FileType className="w-4 h-4" style={{ color: 'var(--primary-color)' }} />
              <span className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>输出格式</span>
            </div>
            <div className="grid grid-cols-4 gap-1.5">
              {formats.map((f) => (
                <button
                  key={f}
                  onClick={() => setTargetFormat(f)}
                  className="px-2 py-1.5 rounded-md text-xs font-medium transition-all text-center"
                  style={{
                    backgroundColor: targetFormat === f ? 'var(--primary-light)' : 'var(--bg-tertiary)',
                    color: targetFormat === f ? 'var(--primary-color)' : 'var(--text-secondary)',
                    border: `1px solid ${targetFormat === f ? 'var(--primary-color)' : 'transparent'}`,
                  }}
                >
                  {f}
                </button>
              ))}
            </div>
          </div>

          <div 
            className="rounded-xl p-4"
            style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}
          >
            <div className="flex items-center gap-2 mb-3">
              <Zap className="w-4 h-4" style={{ color: 'var(--warning-color)' }} />
              <span className="text-sm font-medium" style={{ color: 'var(--text-primary)' }}>快速预设</span>
            </div>
            <div className="grid grid-cols-2 gap-2">
              {[
                { name: '高质量', desc: '大文件，最佳画质', crf: 18, preset: 'slow' },
                { name: '均衡', desc: '画质体积平衡', crf: 23, preset: 'medium' },
                { name: '压缩', desc: '小文件，较快速度', crf: 28, preset: 'fast' },
                { name: '极速', desc: '最快速度，较大文件', crf: 23, preset: 'ultrafast' },
              ].map((p) => (
                <button
                  key={p.name}
                  onClick={() => { setCrf(p.crf); setPreset(p.preset); }}
                  className="p-2 rounded-lg text-left transition-all"
                  style={{
                    backgroundColor: crf === p.crf && preset === p.preset ? 'var(--primary-light)' : 'var(--bg-tertiary)',
                    border: `1px solid ${crf === p.crf && preset === p.preset ? 'var(--primary-color)' : 'transparent'}`,
                  }}
                >
                  <div className="text-xs font-medium" style={{ color: 'var(--text-primary)' }}>{p.name}</div>
                  <div className="text-[10px]" style={{ color: 'var(--text-tertiary)' }}>{p.desc}</div>
                </button>
              ))}
            </div>
          </div>
        </div>

        <div className="col-span-8 space-y-3">
          <CollapsibleSection title="编码设置" icon={<Settings className="w-4 h-4" />}>
            <div className="grid grid-cols-3 gap-4">
              <FormRow label="视频编码器">
                <select 
                  className="w-full rounded-lg px-3 py-2 text-xs outline-none"
                  style={{ backgroundColor: 'var(--bg-primary)', border: '1px solid var(--border-color)', color: 'var(--text-primary)' }}
                  value={vCodec} 
                  onChange={e => setVCodec(e.target.value)}
                >
                  {videoCodecs.map(c => <option key={c}>{c}</option>)}
                </select>
              </FormRow>
              <FormRow label="音频编码器">
                <select 
                  className="w-full rounded-lg px-3 py-2 text-xs outline-none"
                  style={{ backgroundColor: 'var(--bg-primary)', border: '1px solid var(--border-color)', color: 'var(--text-primary)' }}
                  value={aCodec} 
                  onChange={e => setACodec(e.target.value)}
                >
                  {audioCodecs.map(c => <option key={c}>{c}</option>)}
                </select>
              </FormRow>
              <FormRow label="编码预设">
                <select 
                  className="w-full rounded-lg px-3 py-2 text-xs outline-none"
                  style={{ backgroundColor: 'var(--bg-primary)', border: '1px solid var(--border-color)', color: 'var(--text-primary)' }}
                  value={preset} 
                  onChange={e => setPreset(e.target.value)}
                >
                  {presets.map(p => <option key={p}>{p}</option>)}
                </select>
              </FormRow>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <Slider label="CRF (质量)" value={crf} onChange={setCrf} min={0} max={51} />
              <FormRow label="像素格式">
                <select 
                  className="w-full rounded-lg px-3 py-2 text-xs outline-none"
                  style={{ backgroundColor: 'var(--bg-primary)', border: '1px solid var(--border-color)', color: 'var(--text-primary)' }}
                  value={pixFmt} 
                  onChange={e => setPixFmt(e.target.value)}
                >
                  {pixFmts.map(p => <option key={p}>{p}</option>)}
                </select>
              </FormRow>
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="视频参数" icon={<MonitorPlay className="w-4 h-4" />} defaultOpen={mode === 'video'}>
            <div className="grid grid-cols-3 gap-4">
              <FormRow label="分辨率">
                <select 
                  className="w-full rounded-lg px-3 py-2 text-xs outline-none"
                  style={{ backgroundColor: 'var(--bg-primary)', border: '1px solid var(--border-color)', color: 'var(--text-primary)' }}
                  value={resolution} 
                  onChange={e => setResolution(e.target.value)}
                >
                  {resolutions.map(r => <option key={r}>{r}</option>)}
                </select>
              </FormRow>
              <div className="col-span-2">
                <Toggle checked={changeFps} onChange={setChangeFps} label="修改帧率" />
                {changeFps && (
                  <div className="mt-2">
                    <Slider label="帧率 (FPS)" value={fps} onChange={setFps} min={1} max={120} suffix=" fps" />
                  </div>
                )}
              </div>
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="音频参数" icon={<Music2 className="w-4 h-4" />}>
            <div className="grid grid-cols-3 gap-4">
              <Slider label="比特率" value={audioBitrate} onChange={setAudioBitrate} min={64} max={512} suffix=" kbps" />
              <FormRow label="采样率">
                <select 
                  className="w-full rounded-lg px-3 py-2 text-xs outline-none"
                  style={{ backgroundColor: 'var(--bg-primary)', border: '1px solid var(--border-color)', color: 'var(--text-primary)' }}
                  value={sampleRate} 
                  onChange={e => setSampleRate(e.target.value)}
                >
                  {['8000', '16000', '22050', '44100', '48000', '96000'].map(s => <option key={s}>{s} Hz</option>)}
                </select>
              </FormRow>
              <FormRow label="声道">
                <select 
                  className="w-full rounded-lg px-3 py-2 text-xs outline-none"
                  style={{ backgroundColor: 'var(--bg-primary)', border: '1px solid var(--border-color)', color: 'var(--text-primary)' }}
                  value={channels} 
                  onChange={e => setChannels(e.target.value)}
                >
                  <option value="1">单声道</option>
                  <option value="2">立体声</option>
                  <option value="6">5.1 环绕声</option>
                  <option value="8">7.1 环绕声</option>
                </select>
              </FormRow>
            </div>
          </CollapsibleSection>

          <CollapsibleSection title="高级选项" icon={<Gauge className="w-4 h-4" />} defaultOpen={false}>
            <div className="grid grid-cols-3 gap-4">
              <Toggle checked={hwAccel} onChange={setHwAccel} label="硬件加速 (NVENC/QSV/AMF)" />
              <Toggle checked={twoPass} onChange={setTwoPass} label="二次编码 (Two-Pass)" />
              <Toggle checked={fastStart} onChange={setFastStart} label="快速启动 (moov前移)" />
            </div>
          </CollapsibleSection>

          <div 
            className="rounded-xl p-4"
            style={{ backgroundColor: 'var(--bg-secondary)', border: '1px solid var(--border-color)' }}
          >
            <div className="flex items-center gap-4">
              <button 
                onClick={isCurrentModuleProcessing ? handleStop : handleStart} 
                disabled={!isConfigured || !isElectronEnv}
                className="flex items-center gap-2 px-6 py-2.5 rounded-lg text-sm font-semibold text-white disabled:opacity-50 transition-all"
                style={{ background: isCurrentModuleProcessing ? 'linear-gradient(135deg, var(--error-color), #ef4444)' : 'linear-gradient(135deg, var(--primary-color), #8b5cf6)' }}
              >
                {isCurrentModuleProcessing ? <Square className="w-4 h-4" /> : <Sparkles className="w-4 h-4" />}
                {isCurrentModuleProcessing ? '停止' : '开始转换'}
              </button>
              {isCurrentModuleProcessing && currentModuleTask && (
                <div className="flex-1">
                  <ProgressBar value={Math.floor(currentModuleTask.progress)} label="转换进度" />
                </div>
              )}
              {!isCurrentModuleProcessing && (
                <div className="flex items-center gap-2 text-xs" style={{ color: 'var(--text-tertiary)' }}>
                  <Info className="w-3.5 h-3.5" />
                  <span>点击开始按钮执行转换任务</span>
                </div>
              )}
            </div>
            {currentModuleTask && currentModuleTask.logs.length > 0 && (
              <div className="mt-4">
                <Terminal lines={currentModuleTask.logs} />
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
