// 项目重构/src/components/common/ImageViewer.vue
<script setup lang="ts">
import { ref, watch, computed, onMounted, onUnmounted, nextTick } from 'vue';
import { 
  X, ChevronLeft, ChevronRight, ZoomIn, ZoomOut, RotateCw,
  Eye, EyeOff, LayoutGrid, Grid3X3
} from 'lucide-vue-next';

interface ImageItem {
  url: string;
  name?: string;
}

interface Props {
  images: (string | ImageItem)[];
  currentIndex: number;
  isOpen: boolean;
  showThumbnail?: boolean;
  showMask?: boolean;
  defaultZoom?: number;
  scrollMode?: 'navigate' | 'zoom';
}

const props = withDefaults(defineProps<Props>(), {
  showThumbnail: true,
  showMask: true,
  defaultZoom: 1,
  scrollMode: 'zoom',
});

const emit = defineEmits<{
  close: [];
  prev: [];
  next: [];
  jumpTo: [index: number];
}>();

const viewerIndex = ref(props.currentIndex);
const viewerZoom = ref(props.defaultZoom);
const viewerRotation = ref(0);
const viewerMaskVisible = ref(props.showMask);
const thumbnailVisible = ref(props.showThumbnail);
const scrollMode = ref<'navigate' | 'zoom'>(props.scrollMode);

const viewerDrag = ref({
  isDragging: false,
  startX: 0,
  startY: 0,
  translateX: 0,
  translateY: 0
});

const thumbnailContainerRef = ref<HTMLDivElement | null>(null);
const thumbnailScrollLeft = ref(0);
const thumbnailItemWidth = 72;
const thumbnailBuffer = 8;

let scrollRAF: number | null = null;
let lastScrollTime = 0;
const scrollThrottle = 16;

const normalizedImages = computed(() => {
  return props.images.map(img => {
    if (typeof img === 'string') {
      return { url: img, name: `图片` };
    }
    return { url: img.url, name: img.name || `图片` };
  });
});

const currentImage = computed(() => {
  return normalizedImages.value[viewerIndex.value];
});

const visibleThumbnailRange = computed(() => {
  if (!thumbnailContainerRef.value) {
    return { start: 0, end: 10 };
  }
  
  const containerWidth = thumbnailContainerRef.value.clientWidth || 500;
  const scrollLeft = thumbnailScrollLeft.value;
  
  const start = Math.max(0, Math.floor(scrollLeft / thumbnailItemWidth) - thumbnailBuffer);
  const end = Math.min(
    normalizedImages.value.length,
    Math.ceil((scrollLeft + containerWidth) / thumbnailItemWidth) + thumbnailBuffer
  );
  
  return { start, end };
});

const visibleThumbnails = computed(() => {
  const { start, end } = visibleThumbnailRange.value;
  return normalizedImages.value.slice(start, end).map((img, i) => ({
    ...img,
    originalIndex: start + i,
  }));
});

watch(() => props.currentIndex, (newIndex) => {
  viewerIndex.value = newIndex;
  resetViewer();
  nextTick(() => {
    scrollToThumbnail(newIndex);
  });
});

watch(() => props.isOpen, (isOpen) => {
  if (!isOpen) {
    resetViewer();
  } else {
    nextTick(() => {
      scrollToThumbnail(viewerIndex.value);
    });
  }
});

const zoomLevels = [0.25, 0.5, 0.75, 1, 1.25, 1.5, 2, 2.5, 3, 4, 5];

const resetViewer = () => {
  viewerZoom.value = props.defaultZoom;
  viewerRotation.value = 0;
  viewerMaskVisible.value = props.showMask;
  thumbnailVisible.value = props.showThumbnail;
  scrollMode.value = props.scrollMode;
  viewerDrag.value = { isDragging: false, startX: 0, startY: 0, translateX: 0, translateY: 0 };
};

const closeViewer = () => {
  emit('close');
};

const navigateImage = (direction: number) => {
  const newIndex = viewerIndex.value + direction;
  if (newIndex >= 0 && newIndex < props.images.length) {
    if (direction === -1) {
      emit('prev');
    } else {
      emit('next');
    }
    viewerZoom.value = props.defaultZoom;
    viewerRotation.value = 0;
    viewerDrag.value = { isDragging: false, startX: 0, startY: 0, translateX: 0, translateY: 0 };
    scrollToThumbnail(newIndex);
  }
};

const zoomImage = (delta: number) => {
  viewerZoom.value = Math.max(0.25, Math.min(5, viewerZoom.value + delta));
  if (viewerZoom.value === 1) {
    viewerDrag.value.translateX = 0;
    viewerDrag.value.translateY = 0;
  }
};

const stepZoom = (direction: 'in' | 'out') => {
  const currentIndex = zoomLevels.findIndex(z => z === viewerZoom.value);
  let nextIndex;
  if (direction === 'in') {
    nextIndex = Math.min(currentIndex + 1, zoomLevels.length - 1);
  } else {
    nextIndex = Math.max(currentIndex - 1, 0);
  }
  viewerZoom.value = zoomLevels[nextIndex];
  if (viewerZoom.value === 1) {
    viewerDrag.value.translateX = 0;
    viewerDrag.value.translateY = 0;
  }
};

const handleDoubleClick = () => {
  const currentIndex = zoomLevels.findIndex(z => z === viewerZoom.value);
  const nextIndex = (currentIndex + 1) % zoomLevels.length;
  viewerZoom.value = zoomLevels[nextIndex];
  
  if (viewerZoom.value === 1) {
    viewerDrag.value.translateX = 0;
    viewerDrag.value.translateY = 0;
  }
};

const rotateImage = () => {
  viewerRotation.value = (viewerRotation.value + 90) % 360;
};

const toggleMask = () => {
  viewerMaskVisible.value = !viewerMaskVisible.value;
};

const toggleThumbnail = () => {
  thumbnailVisible.value = !thumbnailVisible.value;
};

const toggleScrollMode = () => {
  scrollMode.value = scrollMode.value === 'navigate' ? 'zoom' : 'navigate';
};

const handleMouseDown = (event: MouseEvent) => {
  if (viewerZoom.value > 1) {
    viewerDrag.value.isDragging = true;
    viewerDrag.value.startX = event.clientX - viewerDrag.value.translateX;
    viewerDrag.value.startY = event.clientY - viewerDrag.value.translateY;
    event.preventDefault();
    event.stopPropagation();
  }
};

const handleMouseMove = (event: MouseEvent) => {
  if (viewerDrag.value.isDragging && viewerZoom.value > 1) {
    viewerDrag.value.translateX = event.clientX - viewerDrag.value.startX;
    viewerDrag.value.translateY = event.clientY - viewerDrag.value.startY;
  }
};

const handleMouseUp = () => {
  viewerDrag.value.isDragging = false;
};

const handleWheel = (event: WheelEvent) => {
  event.preventDefault();
  
  if (scrollMode.value === 'zoom') {
    const delta = event.deltaY > 0 ? -0.25 : 0.25;
    zoomImage(delta);
  } else {
    const direction = event.deltaY > 0 ? 1 : -1;
    navigateImage(direction);
  }
};

const handleThumbnailWheel = (event: WheelEvent) => {
  event.preventDefault();
  if (!thumbnailContainerRef.value) return;
  
  const scrollAmount = event.deltaY > 0 ? 100 : -100;
  thumbnailContainerRef.value.scrollBy({
    left: scrollAmount,
    behavior: 'auto'
  });
};

const handleThumbnailScroll = () => {
  const now = performance.now();
  if (now - lastScrollTime < scrollThrottle) {
    return;
  }
  lastScrollTime = now;
  
  if (scrollRAF) {
    cancelAnimationFrame(scrollRAF);
  }
  
  scrollRAF = requestAnimationFrame(() => {
    if (thumbnailContainerRef.value) {
      thumbnailScrollLeft.value = thumbnailContainerRef.value.scrollLeft;
    }
    scrollRAF = null;
  });
};

const scrollToThumbnail = (index: number) => {
  if (!thumbnailContainerRef.value) return;
  
  const scrollPosition = index * thumbnailItemWidth - thumbnailContainerRef.value.clientWidth / 2 + thumbnailItemWidth / 2;
  
  thumbnailContainerRef.value.scrollTo({
    left: scrollPosition,
    behavior: 'smooth'
  });
  
  setTimeout(() => {
    if (thumbnailContainerRef.value) {
      thumbnailScrollLeft.value = thumbnailContainerRef.value.scrollLeft;
    }
  }, 300);
};

const selectThumbnail = (index: number, event: Event) => {
  event.stopPropagation();
  event.preventDefault();
  viewerIndex.value = index;
  emit('jumpTo', index);
  viewerZoom.value = props.defaultZoom;
  viewerRotation.value = 0;
  viewerDrag.value = { isDragging: false, startX: 0, startY: 0, translateX: 0, translateY: 0 };
};

const handleKeyDown = (e: KeyboardEvent) => {
  if (!props.isOpen) return;

  switch (e.key) {
    case 'Escape':
      closeViewer();
      break;
    case 'ArrowLeft':
      navigateImage(-1);
      break;
    case 'ArrowRight':
      navigateImage(1);
      break;
    case '+':
    case '=':
      stepZoom('in');
      break;
    case '-':
      stepZoom('out');
      break;
    case 'r':
    case 'R':
      rotateImage();
      break;
    case 'm':
    case 'M':
      toggleMask();
      break;
    case 't':
    case 'T':
      toggleThumbnail();
      break;
    case 'q':
    case 'Q':
      scrollMode.value = 'navigate';
      break;
    case 'e':
    case 'E':
      scrollMode.value = 'zoom';
      break;
    case '0':
      resetViewer();
      break;
  }
};

onMounted(() => {
  document.addEventListener('keydown', handleKeyDown);
  
  nextTick(() => {
    if (thumbnailContainerRef.value) {
      thumbnailScrollLeft.value = thumbnailContainerRef.value.scrollLeft;
    }
  });
});

onUnmounted(() => {
  document.removeEventListener('keydown', handleKeyDown);
  if (scrollRAF) {
    cancelAnimationFrame(scrollRAF);
  }
});
</script>

<template>
  <Transition name="viewer">
    <div v-if="isOpen" class="image-viewer" :class="{ 'no-mask': !viewerMaskVisible }" @click="closeViewer">
      <div class="viewer-header">
        <div class="viewer-info">
          <h3>{{ currentImage?.name }}</h3>
          <p>{{ viewerIndex + 1 }} / {{ images.length }}</p>
        </div>
        <div class="viewer-actions">
          <button 
            class="viewer-btn scroll-mode-btn" 
            :class="{ active: scrollMode === 'zoom' }"
            @click.stop="toggleScrollMode" 
            :title="scrollMode === 'navigate' ? '切换为缩放模式 (Q/E)' : '切换为导航模式 (Q/E)'"
          >
            <ZoomIn v-if="scrollMode === 'zoom'" :size="18" />
            <ChevronRight v-else :size="18" />
          </button>
          <button class="viewer-btn" @click.stop="toggleMask" :title="viewerMaskVisible ? '隐藏遮罩' : '显示遮罩'">
            <EyeOff v-if="viewerMaskVisible" :size="18" />
            <Eye v-else :size="18" />
          </button>
          <button class="viewer-btn" @click.stop="toggleThumbnail" :title="thumbnailVisible ? '隐藏缩略图' : '显示缩略图'">
            <LayoutGrid v-if="thumbnailVisible" :size="18" />
            <Grid3X3 v-else :size="18" />
          </button>
          <button class="viewer-btn" @click.stop="stepZoom('out')" title="缩小 (-)">
            <ZoomOut :size="18" />
          </button>
          <span class="zoom-level">{{ Math.round(viewerZoom * 100) }}%</span>
          <button class="viewer-btn" @click.stop="stepZoom('in')" title="放大 (+)">
            <ZoomIn :size="18" />
          </button>
          <button class="viewer-btn" @click.stop="rotateImage" title="旋转 (R)">
            <RotateCw :size="18" />
          </button>
          <button class="viewer-btn close-btn" @click.stop="closeViewer" title="关闭 (ESC)">
            <X :size="18" />
          </button>
        </div>
      </div>
      
      <div 
        class="viewer-content"
        @click.stop
        @wheel="handleWheel"
        @mousedown="handleMouseDown"
        @mousemove="handleMouseMove"
        @mouseup="handleMouseUp"
        @mouseleave="handleMouseUp"
        @dblclick="handleDoubleClick"
      >
        <button
          v-if="images.length > 1 && viewerIndex > 0"
          class="nav-btn prev"
          @click.stop="navigateImage(-1)"
        >
          <ChevronLeft :size="32" />
        </button>
        
        <img
          v-if="currentImage"
          :src="currentImage.url"
          :alt="currentImage.name"
          :style="{
            transform: `scale(${viewerZoom}) rotate(${viewerRotation}deg) translate(${viewerDrag.translateX / viewerZoom}px, ${viewerDrag.translateY / viewerZoom}px)`,
            cursor: viewerZoom > 1 ? (viewerDrag.isDragging ? 'grabbing' : 'grab') : 'default',
          }"
          @click.stop
          @dblclick="handleDoubleClick"
          draggable="false"
          loading="lazy"
        />
        
        <button
          v-if="images.length > 1 && viewerIndex < images.length - 1"
          class="nav-btn next"
          @click.stop="navigateImage(1)"
        >
          <ChevronRight :size="32" />
        </button>
      </div>

      <Transition name="thumbnail">
        <div v-if="thumbnailVisible && images.length > 1" class="thumbnail-wrapper">
          <div 
            class="thumbnail-container" 
            @wheel="handleThumbnailWheel" 
            @scroll="handleThumbnailScroll"
            ref="thumbnailContainerRef" 
            @click.stop
          >
            <div 
              class="thumbnail-list" 
              :style="{ 
                width: `${normalizedImages.length * thumbnailItemWidth}px`,
                paddingLeft: `${visibleThumbnailRange.start * thumbnailItemWidth}px`
              }"
            >
              <div
                v-for="image in visibleThumbnails"
                :key="image.originalIndex"
                :class="['thumbnail-item', { active: image.originalIndex === viewerIndex }]"
                @click="selectThumbnail(image.originalIndex, $event)"
              >
                <img :src="image.url" :alt="image.name" loading="lazy" decoding="async" />
              </div>
            </div>
          </div>
        </div>
      </Transition>
    </div>
  </Transition>
</template>

<style scoped>
.image-viewer {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background-color: rgba(0, 0, 0, 0.95);
  z-index: 2000;
  display: flex;
  flex-direction: column;
  transition: background-color 0.3s;
}

.image-viewer.no-mask {
  background-color: transparent;
}

.viewer-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 24px;
  background: linear-gradient(to bottom, rgba(0, 0, 0, 0.8), transparent);
  position: relative;
  z-index: 10;
}

.image-viewer.no-mask .viewer-header {
  background: rgba(0, 0, 0, 0.8);
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.viewer-info h3 {
  font-size: 14px;
  font-weight: 500;
  color: white;
  margin: 0 0 2px 0;
}

.viewer-info p {
  font-size: 12px;
  color: rgba(255, 255, 255, 0.7);
  margin: 0;
}

.viewer-actions {
  display: flex;
  align-items: center;
  gap: 8px;
}

.viewer-btn {
  width: 36px;
  height: 36px;
  border-radius: 8px;
  border: none;
  background-color: rgba(255, 255, 255, 0.1);
  color: white;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s;
}

.viewer-btn:hover {
  background-color: rgba(255, 255, 255, 0.2);
}

.viewer-btn.scroll-mode-btn.active {
  background-color: rgba(var(--primary-color-rgb, 6, 182, 212), 0.8);
}

.viewer-btn.close-btn:hover {
  background-color: rgba(239, 68, 68, 0.8);
}

.zoom-level {
  font-size: 12px;
  color: white;
  min-width: 45px;
  text-align: center;
}

.viewer-content {
  flex: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  position: relative;
  overflow: hidden;
}

.viewer-content img {
  max-width: 90%;
  max-height: 90%;
  object-fit: contain;
  user-select: none;
  will-change: transform;
  transform-origin: center center;
  backface-visibility: hidden;
  perspective: 1000px;
}

.nav-btn {
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  width: 48px;
  height: 48px;
  border-radius: 50%;
  border: none;
  background-color: rgba(255, 255, 255, 0.1);
  color: white;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s;
  z-index: 10;
}

.nav-btn:hover {
  background-color: rgba(255, 255, 255, 0.2);
  transform: translateY(-50%) scale(1.1);
}

.nav-btn.prev {
  left: 24px;
}

.nav-btn.next {
  right: 24px;
}

.thumbnail-wrapper {
  display: flex;
  justify-content: center;
  padding: 0 24px 16px;
}

.thumbnail-container {
  max-width: 500px;
  height: 80px;
  background: rgba(0, 0, 0, 0.6);
  border-radius: 12px;
  overflow-x: auto;
  overflow-y: hidden;
  white-space: nowrap;
  scrollbar-width: none;
  -ms-overflow-style: none;
  padding: 8px;
  will-change: scroll-position;
  -webkit-overflow-scrolling: touch;
  contain: layout style;
  content-visibility: auto;
  overscroll-behavior: contain;
  scroll-behavior: auto;
}

.thumbnail-container::-webkit-scrollbar {
  display: none;
}

.thumbnail-list {
  display: inline-flex;
  gap: 8px;
  align-items: center;
  will-change: transform;
  contain: layout style paint;
  transform: translateZ(0);
  backface-visibility: hidden;
  perspective: 1000px;
}

.thumbnail-item {
  flex-shrink: 0;
  width: 64px;
  height: 64px;
  border-radius: 8px;
  overflow: hidden;
  border: 2px solid transparent;
  cursor: pointer;
  transition: opacity 0.15s ease-out, border-color 0.15s ease-out;
  opacity: 0.6;
  will-change: opacity, border-color;
  contain: strict;
  transform: translateZ(0);
  backface-visibility: hidden;
  perspective: 1000px;
}

.thumbnail-item:hover {
  opacity: 0.9;
}

.thumbnail-item.active {
  border-color: var(--primary-color);
  opacity: 1;
  box-shadow: 0 0 12px rgba(6, 182, 212, 0.5);
}

.thumbnail-item img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  will-change: transform;
  contain: strict;
  transform: translateZ(0);
  backface-visibility: hidden;
  image-rendering: -webkit-optimize-contrast;
}

.viewer-enter-active,
.viewer-leave-active {
  transition: all 0.3s ease;
}

.viewer-enter-from,
.viewer-leave-to {
  opacity: 0;
}

.viewer-enter-from img,
.viewer-leave-to img {
  transform: scale(0.9);
}

.thumbnail-enter-active,
.thumbnail-leave-active {
  transition: all 0.3s ease;
}

.thumbnail-enter-from,
.thumbnail-leave-to {
  opacity: 0;
  transform: translateY(20px);
}
</style>

// src/components/ImageViewer.tsx
import { X, ChevronLeft, ChevronRight, ZoomIn, ZoomOut, RotateCw, RotateCcw } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useState, useEffect, useRef } from 'react';

interface ImageViewerProps {
  images: string[];
  currentIndex: number;
  isOpen: boolean;
  onClose: () => void;
  onPrev: () => void;
  onNext: () => void;
  onJumpTo?: (index: number) => void;
}

export function ImageViewer({ images, currentIndex, isOpen, onClose, onPrev, onNext, onJumpTo }: ImageViewerProps) {
  const [scale, setScale] = useState(1);
  const [rotation, setRotation] = useState(0);
  const [position, setPosition] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const dragStart = useRef({ x: 0, y: 0 });
  const positionStart = useRef({ x: 0, y: 0 });

  useEffect(() => {
    if (isOpen) {
      setScale(1);
      setRotation(0);
      setPosition({ x: 0, y: 0 });
    }
  }, [isOpen, currentIndex]);

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!isOpen) return;
      
      switch (e.key) {
        case 'Escape':
          onClose();
          break;
        case 'ArrowLeft':
          onPrev();
          break;
        case 'ArrowRight':
          onNext();
          break;
        case '+':
        case '=':
          setScale(prev => Math.min(prev + 0.25, 3));
          break;
        case '-':
          setScale(prev => Math.max(prev - 0.25, 0.5));
          break;
      }
    };

    const handleWheel = (e: WheelEvent) => {
      if (!isOpen) return;
      e.preventDefault();
      
      if (e.deltaY < 0) {
        setScale(prev => Math.min(prev + 0.1, 3));
      } else {
        setScale(prev => Math.max(prev - 0.1, 0.5));
      }
    };

    window.addEventListener('keydown', handleKeyDown);
    window.addEventListener('wheel', handleWheel, { passive: false });
    return () => {
      window.removeEventListener('keydown', handleKeyDown);
      window.removeEventListener('wheel', handleWheel);
    };
  }, [isOpen, onClose, onPrev, onNext]);

  const handleZoomIn = () => setScale(prev => Math.min(prev + 0.25, 3));
  const handleZoomOut = () => setScale(prev => Math.max(prev - 0.25, 0.5));
  const handleRotateLeft = () => setRotation(prev => (prev - 90 + 360) % 360);
  const handleRotateRight = () => setRotation(prev => (prev + 90) % 360);
  const handleReset = () => {
    setScale(1);
    setRotation(0);
    setPosition({ x: 0, y: 0 });
  };

  const handleMouseDown = (e: React.MouseEvent) => {
    e.preventDefault();
    setIsDragging(true);
    dragStart.current = { x: e.clientX, y: e.clientY };
    positionStart.current = { ...position };
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (!isDragging) return;
    const deltaX = e.clientX - dragStart.current.x;
    const deltaY = e.clientY - dragStart.current.y;
    setPosition({
      x: positionStart.current.x + deltaX,
      y: positionStart.current.y + deltaY,
    });
  };

  const handleMouseUp = () => {
    setIsDragging(false);
  };

  const handleMouseLeave = () => {
    setIsDragging(false);
  };

  if (!isOpen || images.length === 0) return null;

  return (
    <AnimatePresence>
      {isOpen && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className="fixed inset-0 z-[100] flex items-center justify-center"
          style={{ backgroundColor: 'rgba(0, 0, 0, 0.9)', cursor: isDragging ? 'grabbing' : 'grab' }}
        >
          {/* Right Toolbar */}
          <div 
            className="absolute right-4 top-1/2 -translate-y-1/2 flex flex-col items-center gap-1 p-2 rounded-xl z-10"
            style={{ backgroundColor: 'rgba(0, 0, 0, 0.6)' }}
            onClick={(e) => e.stopPropagation()}
          >
            {/* Close Button */}
            <button
              onClick={onClose}
              className="flex h-10 w-10 items-center justify-center rounded-lg transition-colors text-white hover:bg-red-500/50"
              title="关闭 (Esc)"
            >
              <X size={20} />
            </button>
            
            <div className="w-full h-px my-1" style={{ backgroundColor: 'rgba(255, 255, 255, 0.2)' }} />
            
            {/* Zoom Controls */}
            <button
              onClick={handleZoomIn}
              className="flex h-10 w-10 items-center justify-center rounded-lg transition-colors text-white hover:bg-white/20"
              title="放大 (+)"
            >
              <ZoomIn size={20} />
            </button>
            
            <div className="text-white text-xs py-1 text-center min-w-[40px]" style={{ color: 'rgba(255, 255, 255, 0.8)' }}>
              {Math.round(scale * 100)}%
            </div>
            
            <button
              onClick={handleZoomOut}
              className="flex h-10 w-10 items-center justify-center rounded-lg transition-colors text-white hover:bg-white/20"
              title="缩小 (-)"
            >
              <ZoomOut size={20} />
            </button>
            
            <div className="w-full h-px my-1" style={{ backgroundColor: 'rgba(255, 255, 255, 0.2)' }} />
            
            {/* Rotate Controls */}
            <button
              onClick={handleRotateLeft}
              className="flex h-10 w-10 items-center justify-center rounded-lg transition-colors text-white hover:bg-white/20"
              title="向左旋转"
            >
              <RotateCcw size={20} />
            </button>
            
            <button
              onClick={handleRotateRight}
              className="flex h-10 w-10 items-center justify-center rounded-lg transition-colors text-white hover:bg-white/20"
              title="向右旋转"
            >
              <RotateCw size={20} />
            </button>
            
            <div className="w-full h-px my-1" style={{ backgroundColor: 'rgba(255, 255, 255, 0.2)' }} />
            
            {/* Reset */}
            <button
              onClick={handleReset}
              className="flex h-10 w-10 items-center justify-center rounded-lg transition-colors text-white hover:bg-white/20"
              title="重置"
            >
              <span className="text-xs font-medium">重置</span>
            </button>
            
            <div className="w-full h-px my-1" style={{ backgroundColor: 'rgba(255, 255, 255, 0.2)' }} />
            
            {/* Image Counter */}
            <div className="text-white text-xs font-medium py-2 px-3 text-center" style={{ color: 'rgba(255, 255, 255, 0.9)' }}>
              {currentIndex + 1} / {images.length}
            </div>
          </div>

          {/* Navigation Buttons */}
          {images.length > 1 && (
            <>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onPrev();
                }}
                className="absolute left-4 top-1/2 -translate-y-1/2 flex h-12 w-12 items-center justify-center rounded-full transition-colors text-white hover:bg-white/20 z-10"
                style={{ backgroundColor: 'rgba(0, 0, 0, 0.5)' }}
              >
                <ChevronLeft size={24} />
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  onNext();
                }}
                className="absolute right-20 top-1/2 -translate-y-1/2 flex h-12 w-12 items-center justify-center rounded-full transition-colors text-white hover:bg-white/20 z-10"
                style={{ backgroundColor: 'rgba(0, 0, 0, 0.5)' }}
              >
                <ChevronRight size={24} />
              </button>
            </>
          )}

          {/* Image */}
          <motion.div
            key={currentIndex}
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.9 }}
            transition={{ duration: 0.2 }}
            className="flex items-center justify-center w-full h-full overflow-hidden"
            style={{ paddingRight: '80px', paddingLeft: '16px' }}
            onClick={(e) => e.stopPropagation()}
            onMouseDown={handleMouseDown}
            onMouseMove={handleMouseMove}
            onMouseUp={handleMouseUp}
            onMouseLeave={handleMouseLeave}
          >
            <img
              src={images[currentIndex]}
              alt={`图片 ${currentIndex + 1}`}
              className="max-w-full max-h-full object-contain transition-transform duration-75"
              style={{
                transform: `translate(${position.x}px, ${position.y}px) scale(${scale}) rotate(${rotation}deg)`,
                cursor: isDragging ? 'grabbing' : 'grab',
              }}
              draggable={false}
            />
          </motion.div>

          {/* Thumbnails */}
          {images.length > 1 && (
            <div 
              className="absolute bottom-4 left-1/2 -translate-x-1/2 flex gap-2 p-2 rounded-lg z-10"
              style={{ backgroundColor: 'rgba(0, 0, 0, 0.7)' }}
              onClick={(e) => e.stopPropagation()}
            >
              {images.map((img, idx) => (
                <button
                  key={idx}
                  onClick={() => onJumpTo?.(idx)}
                  className={`relative h-12 w-12 rounded overflow-hidden transition-all ${
                    idx === currentIndex ? 'ring-2 ring-white' : 'opacity-60 hover:opacity-100'
                  }`}
                >
                  <img src={img} alt="" className="h-full w-full object-cover" />
                </button>
              ))}
            </div>
          )}
        </motion.div>
      )}
    </AnimatePresence>
  );
}
